timezone: Europe/Zurich
user: pi
root_dirs:
  pihole: /home/pi/pihole
  maintenance: /home/pi/maintenance
  rss: /home/pi/rss
  proxy: /home/pi/proxy
  jupyter: /home/pi/jupyter

discovery_network:
  name: discovery
