data_mountpoint: /applications
# application_root: /home/pi
application_root: "{{ data_mountpoint }}"

timezone: Europe/Zurich
user: realmar
user_id: 1000
user_password: "{{ base_system_pi_password }}"

root_dirs_pihole: "{{ application_root }}/pihole"
root_dirs_maintenance: "{{ application_root }}/maintenance"
root_dirs_rss: "{{ application_root }}/rss"
root_dirs_proxy: "{{ application_root }}/proxy"
root_dirs_jupyter: "{{ application_root }}/jupyter"
root_dirs_discord: "{{ application_root }}/discord"
root_dirs_personal_website: "{{ application_root }}/realmar.net"
root_dirs_home_automation: "{{ application_root }}/home_automation"
root_dirs_datastore: "{{ application_root }}/datastore"
root_dirs_matrix_server: "{{ application_root }}/matrix_server"
root_dirs_wireguard: "{{ application_root }}/wireguard"
root_dirs_workflow_automation: "{{ application_root }}/workflow_automation"
root_dirs_dyndns: "{{ application_root }}/dyndns"

# ZHAW
root_dirs_zhaw_iot1: "{{ application_root }}/zhaw_iot1"

network_names_discovery: discovery
network_names_datastore: datastore

discovery_network:
  name: "{{ network_names_discovery }}"

datastore_network:
  name: "{{ network_names_datastore }}"

dns_public_root: "realmar.net"
dns_internal_root: "internal.realmar.net"

dns_sub_domains_login: "login.{{ dns_public_root }}"
dns_sub_domains_smarthome: "smarthome.{{ dns_public_root }}"
dns_sub_domains_element: "element.{{ dns_public_root }}"
dns_sub_domains_prometheus: "prometheus.{{ dns_public_root }}"
dns_sub_domains_jobbernetes: "jobbernetes.{{ dns_public_root }}"
dns_sub_domains_backup: "backup.{{ dns_public_root }}"
dns_sub_domains_n8n: "n8n.{{ dns_public_root }}"
dns_sub_domains_vector: "vector.{{ dns_public_root }}"
# dns_sub_domains_kibana: "kibana.{{ dns_public_root }}"

all_dns:
  - "{{ dns_public_root }}"
  - "{{ dns_internal_root }}"
  - "{{ dns_sub_domains_login }}"
  - "{{ dns_sub_domains_smarthome }}"
  - "{{ dns_sub_domains_element }}"
  - "{{ dns_sub_domains_prometheus }}"
  - "{{ dns_sub_domains_jobbernetes }}"
  - "{{ dns_sub_domains_backup }}"
  - "{{ dns_sub_domains_n8n }}"
  - "{{ dns_sub_domains_vector }}"
  # - "{{ dns_sub_domains_kibana }}"

letsencrypt_resolver_name: lets_encrypt

global_cert_dir: "{{ application_root }}/tls_certificates"

private_docker_registry: 192.168.1.128:5000
