data_mountpoint: /data
application_root: /home/pi
# application_root: "{{ data_mountpoint }}"

timezone: Europe/Zurich
user: pi
user_password: "{{ base_system_pi_password }}"
root_dirs:
  pihole: "{{ application_root }}/pihole"
  maintenance: "{{ application_root }}/maintenance"
  rss: "{{ application_root }}/rss"
  proxy: "{{ application_root }}/proxy"
  jupyter: "{{ application_root }}/jupyter"
  discord: "{{ application_root }}/discord"
  personal_website: "{{ application_root }}/realmar.net"
  home_automation: "{{ application_root }}/home_automation"
  datastore: "{{ application_root }}/datastore"
  matrix_server: "{{ application_root }}/matrix_server"

  # ZHAW
  zhaw_iot1: "{{ application_root }}/zhaw_iot1"

network_names:
  discovery: discovery
  datastore: datastore

discovery_network:
  name: "{{ network_names.discovery }}"

datastore_network:
  name: "{{ network_names.datastore }}"

dns:
  public:
    root: "realmar.net"
  internal:
    root: "internal.realmar.net"

dns_sub_domains:
  login: "login.{{ dns.public.root }}"
  smarthome: "smarthome.{{ dns.public.root }}"

all_dns:
  - "{{ dns.public.root }}"
  - "{{ dns.internal.root }}"
  - "{{ dns_sub_domains.login }}"
  - "{{ dns_sub_domains.smarthome }}"

letsencrypt_resolver_name: lets_encrypt

global_cert_dir: "{{ application_root }}/tls_certificates"

private_docker_registry: 192.168.1.128:5000
