user: pi
root_dirs:
  pihole: /home/pi/pihole
  netdata: /home/pi/netdata
docker_volume_root: /var/lib/docker/volumes

networks:
  enable_ipv6: no
  host:
    v4:
      netaddress: 192.168.1.0
      netmask: 255.255.255.0

  pihole:
    v4:
      subnet: 172.16.1.0/24
      netaddress: 172.16.1.0
      netmask: 255.255.255.0
      gateway: 172.16.1.1
    v6:
      subnet: 2a02:120b:2c06:57df::/64
      gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
    name: pihole-net

  vpn:
    v4:
      subnet: 172.16.2.0/24
      netaddress: 172.16.2.0
      netmask: 255.255.255.0
      gateway: 172.16.2.1
    v6:
      subnet: 2a02:120b:2c06:57de::/64
      gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
    name: vpn-net

volumes:
  pihole:
    main:
      name: main_config
      local_folder: "{{ root_dirs.pihole }}/etc-pihole"
      mount: /etc/pihole/
    dnsmasq:
      name: dnsmasq_config
      local_folder: "{{ root_dirs.pihole }}/etc-dnsmasq.d"
      mount: /etc/dnsmasq.d/
  vpn:
    config:
      name: ovpn_config
      local_folder: "{{ root_dirs.pihole }}/etc-openvpn"
      mount: /etc/openvpn

pihole:
  name: pihole
  ipv4: 172.16.1.20
  ipv6: 2a02:120b:2c06:57df::20
  use_host_net: yes

openvpn:
  name: openvpn
  ipv4: 172.16.2.20
  ipv6: 2a02:120b:2c06:57de::20
  dns: vpn.realmar.net

  conf:
    server:
      file: openvpn.conf
      netaddress: 192.168.255.0
      netmask: 255.255.255.0
      route_home_network: yes
    client:
      only_dns_over_vpn: yes
