user: pi
root_dirs:
  pihole: /home/pi/pihole
  netdata: /home/pi/netdata
docker_volume_root: /var/lib/docker/volumes

networks:
  host:
    v4:
      netaddress: 192.168.1.0
      netmask: 255.255.255.0
      gateway: 192.168.1.1
    v6:
      subnet: 2a02:120b:2c06:57d0::/64
      netmask: 64
      gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6

  pihole:
    v4:
      subnet: 172.16.1.0/24
      netaddress: 172.16.1.0
      netmask: 255.255.255.0
      gateway: 172.16.1.1
    v6:
      enable: "{{ True if 'development' not in group_names else False }}"
      subnet: 2a02:120b:2c06:57df::/64
      netmask: 64
      gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
    name: pihole-net

  vpn:
    v4:
      subnet: 172.16.2.0/24
      netaddress: 172.16.2.0
      netmask: 255.255.255.0
      gateway: 172.16.2.1
    v6:
      enable: yes
      subnet: 2a02:120b:2c06:57de::/64
      netmask: 64
      gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
    name: vpn-net

volumes:
  pihole:
    main:
      name: main_config
      local_folder: "{{ root_dirs.pihole }}/etc-pihole"
      mount: /etc/pihole/
    dnsmasq:
      name: dnsmasq_config
      local_folder: "{{ root_dirs.pihole }}/etc-dnsmasq.d"
      mount: /etc/dnsmasq.d/
  vpn:
    config:
      name: ovpn_config
      local_folder: "{{ root_dirs.pihole }}/etc-openvpn"
      mount: /etc/openvpn

pihole:
  name: pihole
  ipv4: 172.16.1.20
  ipv6: 2a02:120b:2c06:57df::20
  use_host_net: yes # "{{ True if 'development' not in group_names else False }}"
  network: "{{ networks.pihole }}"

openvpn:
  name: openvpn
  ipv4: 172.16.2.20
  ipv6: 2a02:120b:2c06:57de::20
  use_host_net: no # "{{ True if 'development' not in group_names else False }}"
  network: "{{ networks.vpn }}"

  conf:
    dns: vpn.realmar.net

    ca_cert_bits: 4096
    tls_cipher: TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384
    cipher: AES-256-GCM
    auth: SHA512

    server:
      file: openvpn.conf
      netaddress: 192.168.255.0
      netmask: 255.255.255.0
      route_home_network: yes
    client:
      only_dns_over_vpn: yes

containers:
  - "{{ pihole }}"
  - "{{ openvpn }}"
