timezone: Europe/Zurich
user: pi
root_dirs:
  pihole: /home/pi/pihole
  maintenance: /home/pi/maintenance
  rss: /home/pi/rss
  proxy: /home/pi/proxy
  jupyter: /home/pi/jupyter

discovery_network:
  name: discovery

sso_auth:
  ipv4: 172.16.20.80

dns_root: realmar.net
sub_dns:
  login: "login.{{ dns_root }}"

all_dns:
  - "{{ dns_root }}"
  - "{{ sub_dns.login }}"
