timezone: Europe/Zurich
user: pi
root_dirs:
  pihole: /home/pi/pihole
  maintenance: /home/pi/maintenance
  rss: /home/pi/rss
  proxy: /home/pi/proxy
  jupyter: /home/pi/jupyter
  discord: /home/pi/discord
  personal_website: /home/pi/realmar.net
  home_automation: /home/pi/home_automation

discovery_network:
  name: discovery

sso_auth:
  ipv4: 172.16.20.80

dns:
  public:
    root: "realmar.net"
  internal:
    root: "internal.realmar.net"

dns_sub_domains:
  login: "login.{{ dns.public.root }}"
  smarthome: "smarthome.{{ dns.public.root }}"

all_dns:
  - "{{ dns.public.root }}"
  - "{{ dns.internal.root }}"
  - "{{ dns_sub_domains.login }}"
  - "{{ dns_sub_domains.smarthome }}"

letsencrypt_resolver_name: lets_encrypt
