- block:
    - include_tasks: standard_service.yml
      vars:
        usr: "{{ user }}"
        root_dir: "{{ root_dirs_maintenance }}"
        dirs:
          - "{{ duplicati_volumes_config.local_folder }}"
          - "{{ duplicati_volumes_backup_target_home_user.local_folder }}"
          - "{{ portainer_volumes_data.local_folder }}"
  tags:
    - compose_file
    - maintenance_compose_file

- name: Copy configs
  template:
    src: "{{ item }}"
    dest: "{{ root_dirs_maintenance }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    - netdata.conf
  tags: maintenance_config

- block:
  - include_tasks: backup_helper.yml
  tags: backup_helper

- block:
    - include_tasks: fix_permissions.yml
      vars:
        items: "{{ maintenance_folders_permissions }}"
  tags:
    - fix_permissions
    - maintenance_fix_permissions
    - compose_file
    - maintenance_compose_file
