{% import "docker/misc.jinja2" as dm with context -%}
{% import "docker/network.jinja2" as dn with context -%}
{% import "docker/volumes.jinja2" as dv with context -%}

{% set drive_vols = [ drive_volumes_data ] %}

version: "3"
services:
  {{ dm.service(
    'filebrowser',
    'filebrowser/filebrowser')|indent(width = 2) }}
    user: "{{ fileserver_user_id }}:{{ fileserver_user_id }}"
    {{ lookup('traefik', {
      'service_name': 'filebrowser',
      'domain': dns_sub_domains_drive,
      'port': 80,
      'use_dns_root': True })|indent(width = 4) }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dv.volumes_section_complete(drive_vols)|indent(width = 4) }}
      - {{ root_dirs_drive }}/filebrowser.db:/database.db
      - {{ root_dirs_drive }}/.filebrowser.json:/.filebrowser.json

{{ dn.discovery_networks_declaration() }}
{{ dv.volumes_declaration(drive_vols) }}

{#

# amd64 only

{% set drive_vols = [ drive_volumes_data, drive_volumes_config ] %}
{% set db_vols = [ drive_db_data ] %}

version: "3"
services:
  # https://github.com/linuxserver/docker-pydio-cells
  {{ dm.service(
    'pydio',
    dm.private_image('ghcr.io/linuxserver/pydio-cells'))|indent(width = 2) }}
    environment:
      PUID: "{{ fileserver_user_id }}"
      PGID: "{{ fileserver_user_id }}"
      EXTERNALURL: "{{ dns_sub_domains_drive }}"
      TZ: {{ timezone }}
    {{ lookup('traefik', {
      'service_name': 'pydio',
      'domain': dns_sub_domains_drive,
      'port': 8080,
      'use_dns_root': True })|indent(width = 4) }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
      drive:
    {{ dv.volumes_section_complete(drive_vols)|indent(width = 4) }}

  {{ dm.service(
    'mariadb',
    'ghcr.io/linuxserver/mariadb:alpine')|indent(width = 2) }}
    environment:
      PUID: "{{ fileserver_user_id }}"
      PGID: "{{ fileserver_user_id }}"
      MYSQL_DATABASE: "{{ drive_db_name }}"
      MYSQL_USER: "{{ drive_db_username }}"
      MYSQL_PASSWORD: "{{ drive_db_user_password }}"
      MYSQL_ROOT_PASSWORD: "{{ drive_db_root_password }}"
      TZ: {{ timezone }}
    networks:
      drive:
    {{ dv.volumes_section_complete(db_vols)|indent(width = 4) }}

{{ dn.discovery_networks_declaration() }}
  drive:

{{ dv.volumes_declaration(drive_vols + db_vols) }}
#}
