- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - openssl

- include_tasks: create_self_signed_cert.yml
  vars:
    privatekey_path: "{{ tls_self_signed_private_key_dir }}"
    csr_path: "{{ tls_self_signed_cert_request_dir }}"
    pem_path: "{{ tls_self_signed_cert_dir }}"
    common_name: "{{ dns_internal_root if not is_dev else dns_public_root }}"
