- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - openssl

- include_tasks: create_self_signed_cert.yml
  vars:
    privatekey_path: "{{ tls.self_signed.private_key_dir }}"
    csr_path: "{{ tls.self_signed.cert_request_dir }}"
    pem_path: "{{ tls.self_signed.cert_dir }}"
