{% import "password_gen.jinja2" as gen with context -%}
{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/misc.jinja2' as dm with context -%}
{% import 'traefik/http.jinja2' as traefik with context -%}

{% set vols_matrix_server = [ matrix_server.volumes.data ] %}
{% set vols_db = [ matrix_server_db.volumes.data ] %}
{% set service_name = 'matrix_synapse' %}

version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: {{ matrix_server_db.db_user }}
      POSTGRES_PASSWORD: '{{ gen.pw("matrix_server_db") }}'
      POSTGRES_DB: na_default
    {{ dv.volumes_section_complete(vols_db)|indent(width = 4) }}
      - {{ root_dirs.matrix_server }}/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      {{ matrix_server.networks.name }}:
    {{ dm.common()|indent(width = 4) }}

  redis:
    image: redis:latest
    networks:
      {{ matrix_server.networks.name }}:
    {{ dm.common()|indent(width = 4) }}

  server:
    image: black0/synapse:latest
    container_name: matrix_server
    environment:
      UID: '{{ matrix_server.user }}'
      GID: '{{ matrix_server.user }}'
    {{ traefik.declare_labels_mount_path(dns.public.root, service_name, "/_matrix/", 8008,
        traefik.minimal_middlewares_no_auth,
        [ 'websecure', 'matrix_alt' ]
      )|indent(width = 4) }}
      {{ traefik.use_letsencrypt(service_name) }}
    {{ dv.volumes_section_complete(vols_matrix_server)|indent(width = 4) }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
      {{ matrix_server.networks.name }}:
    {{ dm.common()|indent(width = 4) }}
    depends_on:
      - db
      - redis

  turnserver:
    image: killua99/coturn:latest
{#
    ports:
      # P2P Connections
      - 49152-65535:49152-65535/udp

      # Unencrypted
      # - 3478:3478
      - 3478:3478/udp

      # Encrypted
      # - 5349:5349
      - 5349:5349/udp
#}
    network_mode: host
    tmpfs:
      - /var/lib/coturn
    volumes:
      - {{ root_dirs.matrix_server }}/turnserver.conf:/etc/coturn/turnserver.conf
      - {{ global_cert_dir }}/realmar.net.crt:/opt/certificates/realmar.net.crt
      - {{ global_cert_dir }}/realmar.net.pem:/opt/certificates/realmar.net.pem
{#
    networks:
      {{ matrix_server.networks.name }}:
 {#     ipv4_address: {{ turnserver.ipv4 }} #}
#}
    {{ dm.common()|indent(width = 4) }}

{#{{ dn.networks_declaration([ discovery_network, matrix_server.networks ]) }}#}
{{ dn.networks_declaration([ discovery_network ]) }}
  {{ matrix_server.networks.name }}:
{#
  matrix_net:
    driver: macvlan
    driver_opts:
      parent: {{ host.public_interface }}.30
    ipam:
      config:
        #- subnet: "172.16.90.0/24"
        - subnet: "{{ host.networks.v4.subnet }}"
#}

{{ dv.volumes_declaration(vols_matrix_server + vols_db) }}
