{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/misc.jinja2' as dm with context -%}

{% set vols_matrix_server = [ matrix_server_volumes_data ] %}
{% set vols_db = [ matrix_server_db_volumes_data ] %}
{% set vols_telegram = [ matrix_server_telegram_volumes_data ] %}
{% set vols_signal = [ matrix_server_signal_volumes_data ] %}
{% set vols_signald = [ matrix_server_signald_volumes_data ] %}
{% set vols_instagram = [ matrix_server_instagram_volumes_data ] %}
{% set vols_twitter = [ matrix_server_twitter_volumes_data ] %}
{% set vols_whatsapp = [ matrix_server_whatsapp_volumes_data ] %}

{% set vols_bridges = vols_telegram + vols_signal + vols_instagram + vols_twitter + vols_whatsapp %}
{% set vols_bridges_synapse_mounts = [
  ms_vol_bridge_telegram,
  ms_vol_bridge_signal,
  ms_vol_bridge_instagram,
  ms_vol_bridge_twitter,
  ms_vol_bridge_whatsapp ] %}

{% set vols_all = vols_matrix_server + vols_db + vols_bridges + vols_signald %}

{% set mautrix_ref = {
  'telegram': {
    'container_name': matrix_server_telegram_container_name,
    'vols': vols_telegram
  },
  'signal': {
    'container_name': matrix_server_signal_container_name,
    'user': matrix_server_signal_user_id,
    'vols': vols_signal + vols_signald
  },
  'instagram': {
    'container_name': matrix_server_instagram_container_name,
    'vols': vols_instagram
  },
  'twitter': {
    'container_name': matrix_server_twitter_container_name,
    'vols': vols_twitter
  },
  'whatsapp': {
    'container_name': matrix_server_whatsapp_container_name,
    'vols': vols_whatsapp
  }
} %}

{% macro synapse_nets_list() %}
{{ network_names_datastore }}:
{{ matrix_server_networks.name }}:
{% endmacro %}

{% macro synapse_nets() %}
networks:
  {{ synapse_nets_list()|indent(width = 2) }}
{% endmacro %}

{% macro mautrix(name, more) %}
mautrix_{{ name }}:
  container_name: {{ mautrix_ref[name].container_name }}
{% if 'user' in mautrix_ref[name] %}
  user: '{{ mautrix_ref[name].user }}'
{% endif %}
  image: dock.mau.dev/tulir/mautrix-{{ name }}:latest
  {{ dv.volumes_section_complete(mautrix_ref[name].vols)|indent(width = 2) }}
  {{ synapse_nets()|indent(width = 2) }}
  {{ dm.journald_logging()|indent(width = 2) }}
  {{ dm.common()|indent(width = 2) }}
  depends_on:
    - synapse
{% if more is defined and more['depends_on'] %}
{% for d in more['depends_on'] %}
    - {{ d }}
{% endfor %}
{% endif %}
{% endmacro %}

{% set service_name = 'matrix_synapse' %}
{% set wk_path = "/.well-known/matrix/" %}
{% set wk_service_name = "matrix_well_known" %}

version: "3"
services:

{# https://github.com/matrix-org/synapse/tree/master/docker #}
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    environment:
      UID: '{{ matrix_server_user }}'
      GID: '{{ matrix_server_user }}'
      TZ: {{ timezone }}
    {{ lookup('traefik', { 'service_name': 'matrix_synapse', 'strip_path': False, 'use_auth': False, 'path': '/_matrix/', 'port': 8008 })|indent(width = 4) }}
    {{ dv.volumes_section_complete(vols_matrix_server + vols_bridges_synapse_mounts)|indent(width = 4) }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
      {{ synapse_nets_list()|indent(width = 6) }}
    {{ dm.common()|indent(width = 4) }}
    depends_on:
      - db

################################################################################
##Bridges#######################################################################
################################################################################

  {{ mautrix('telegram')|indent(width = 2) }}

  {{ mautrix('whatsapp')|indent(width = 2) }}

  {{ mautrix('instagram')|indent(width = 2) }}

  {{ mautrix('twitter')|indent(width = 2) }}

  {{ mautrix('signal',
    {
      'depends_on': [ 'signald' ]
    })|indent(width = 2)
  }}

  signald:
    container_name: signald
    image: docker.io/finn/signald:{{ 'latest' if is_dev else 'aarch64-latest' }}
    user: '{{ matrix_server_signal_user_id }}'
    {{ dv.volumes_section_complete(vols_signald)|indent(width = 4) }}
    {{ synapse_nets()|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}
    depends_on:
      - synapse

################################################################################
################################################################################
################################################################################

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: {{ matrix_server_db_user }}
      POSTGRES_PASSWORD: '{{ matrix_server_db_password }}'
      POSTGRES_DB: na_default
    {{ dv.volumes_section_complete(vols_db)|indent(width = 4) }}
      - {{ root_dirs_matrix_server }}/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      {{ matrix_server_networks.name }}:
    {{ dm.common()|indent(width = 4) }}

  element_web:
    image: 'bubuntux/element-web'
    {{ lookup('traefik', { 'service_name': 'element_web', 'domain': dns_sub_domains_element, 'use_dns_root': True, 'use_auth': False })|indent(width = 4) }}
    {{ dv.volumes_section_complete()|indent(width = 4) }}
      - {{ root_dirs_matrix_server }}/element_web_config.json:/etc/element-web/config.json:ro
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}
    depends_on:
      - synapse

  turnserver:
    image: killua99/coturn:latest
    network_mode: host
    tmpfs:
      - /var/lib/coturn
    volumes:
      - {{ root_dirs_matrix_server }}/turnserver.conf:/etc/coturn/turnserver.conf
      - {{ global_cert_dir }}/realmar.net.crt:/opt/certificates/realmar.net.crt
      - {{ global_cert_dir }}/realmar.net.pem:/opt/certificates/realmar.net.pem
    {{ dm.common()|indent(width = 4) }}

  well_known:
    image: nginx:latest
    {{ lookup('traefik', { 'service_name': 'matrix_well_known', 'use_defaults': False, 'path': wk_path,
      'renderers': {
        'replace_path_regex': {
          "regex": "^" + wk_path + "(server|client)$",
          "replacement": "/well-known_$1.json"
        },
        'add_cors': {
          "originlist": "*",
          "methods": "GET,POST,PUT,DELETE,OPTIONS",
          "allowheaders": "Origin,X-Requested-With,Content-Type,Accept,Authorization"
        }
    } })|indent(width = 4) }}
    volumes:
{% for file in [ "well-known_server.json", "well-known_client.json" ] %}
      - {{ root_dirs_matrix_server }}/{{ file }}:/usr/share/nginx/html/{{ file }}:ro
{% endfor %}
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}

{{ dn.networks_declaration([ discovery_network, datastore_network ]) }}
  {{ matrix_server_networks.name }}:

{{ dv.volumes_declaration(vols_all) }}
