{% import "password_gen.jinja2" as gen with context -%}
{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/misc.jinja2' as dm with context -%}
{% import 'traefik/http.jinja2' as traefik with context -%}

{% set vols_matrix_server = [ matrix_server.volumes.data ] %}
{% set vols_db = [ matrix_server_db.volumes.data ] %}
{% set service_name = 'matrix_synapse' %}
{% set nginx_name = 'matrix_well_known' %}

version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: {{ matrix_server_db.db_user }}
      POSTGRES_PASSWORD: '{{ gen.pw("matrix_server_db") }}'
      POSTGRES_DB: na_default
    {{ dv.volumes_section_complete(vols_db)|indent(width = 4) }}
      - {{ root_dirs.matrix_server }}/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      {{ matrix_server.networks.name }}:
    {{ dm.common()|indent(width = 4) }}

  redis:
    image: redis:latest
    networks:
      {{ matrix_server.networks.name }}:
    {{ dm.common()|indent(width = 4) }}

  server:
    image: black0/synapse:latest
    container_name: matrix_server
    environment:
      UID: '{{ matrix_server.user }}'
      GID: '{{ matrix_server.user }}'
{#      [ 'websecure', 'matrix_alt' ] #}
    {{ traefik.declare_labels_mount_path(dns.public.root, service_name, "/_matrix/", 8008,
        traefik.minimal_middlewares_no_auth,
        [ 'websecure' ]
      )|indent(width = 4) }}
      {{ traefik.use_letsencrypt(service_name) }}
    {{ dv.volumes_section_complete(vols_matrix_server)|indent(width = 4) }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
      {{ matrix_server.networks.name }}:
    {{ dm.common()|indent(width = 4) }}
    depends_on:
      - db
      - redis

  turnserver:
    image: killua99/coturn:latest
    network_mode: host
    tmpfs:
      - /var/lib/coturn
    volumes:
      - {{ root_dirs.matrix_server }}/turnserver.conf:/etc/coturn/turnserver.conf
      - {{ global_cert_dir }}/realmar.net.crt:/opt/certificates/realmar.net.crt
      - {{ global_cert_dir }}/realmar.net.pem:/opt/certificates/realmar.net.pem
    {{ dm.common()|indent(width = 4) }}

  well_known:
    image: nginx:latest
    {{ traefik.declare_labels_mount_path(dns.public.root, nginx_name, "/.well-known/matrix/server", 80,
        [
          {
            "mw": traefik.replace_path,
            "args": { "path": "/well-known_server.json" }
          }
        ],
        [ 'websecure' ]
      )|indent(width = 4) }}
      {{ traefik.use_letsencrypt(nginx_name) }}
    volumes:
      - {{ root_dirs.matrix_server }}/well-known_server.json:/usr/share/nginx/html/well-known_server.json:ro
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}

{{ dn.networks_declaration([ discovery_network ]) }}
  {{ matrix_server.networks.name }}:

{{ dv.volumes_declaration(vols_matrix_server + vols_db) }}
