remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db={{ prometheus_user_influxdb_name }}"

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db={{ prometheus_user_influxdb_name }}"

scrape_configs:

  - job_name: "node"
    static_configs:
      - targets: [ "{{ host_ipv4 }}:9100" ]

  - job_name: "influxdb_internal"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "influxdb_stats_exporter:9424" ]

  - job_name: "synapse"
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: [ "synapse:9000" ]

  - job_name: "mautrix_telegram"
    static_configs:
      - targets: [ "{{ matrix_server_telegram_container_name }}:9000" ]

  - job_name: "mautrix_whatsapp"
    static_configs:
      - targets: [ "{{ matrix_server_whatsapp_container_name }}:9000" ]

  - job_name: "mautrix_signal"
    static_configs:
      - targets: [ "{{ matrix_server_signal_container_name }}:9000" ]

  - job_name: "mautrix_instagram"
    static_configs:
      - targets: [ "{{ matrix_server_instagram_container_name }}:9000" ]

  - job_name: "mautrix_twitter"
    static_configs:
      - targets: [ "{{ matrix_server_twitter_container_name }}:9000" ]

  - job_name: "mautrix_facebook"
    static_configs:
      - targets: [ "{{ matrix_server_facebook_container_name }}:9000" ]

  - job_name: "pihole"
    static_configs:
      - targets: [ "{{ pihole_prometheus_exporter_container_name }}:{{ pihole_prometheus_exporter_port }}" ]

  - job_name: "n8n"
    static_configs:
      - targets: [ "{{ workflow_automation_container_name }}:{{ workflow_automation_port }}" ]
