remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db={{ prometheus_user_influxdb_name }}"

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db={{ prometheus_user_influxdb_name }}"
