remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db={{ prometheus_user_influxdb_name }}"

remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db={{ prometheus_user_influxdb_name }}"

scrape_configs:

  - job_name: "synapse"
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: [ "synapse:9000" ]

  - job_name: "mautrix_telegram"
    metrics_path: "/"
    static_configs:
      - targets: [ "{{ matrix_server_telegram_container_name }}:9000" ]
