version: 0.1
log:
  fields:
    service: registry

storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
  filesystem:
    rootdirectory: {{ registry.volumes.data.mount }}

http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: [ '*' ]
    Access-Control-Allow-Methods: [ 'HEAD', 'GET', 'OPTIONS', 'DELETE' ]
    Access-Control-Expose-Headers: [ 'Docker-Content-Digest' ]

redis:
  addr: redis:6379
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
