- name: Install base packages
  apt:
    name: [ 'python3', 'python3-dev', 'python3-pip', 'python-dev', 'bash-completion', 'git', 'htop', 'lsb-release', 'ncdu', 'tree', 'vim', 'wget', 'aptitude', 'fail2ban', 'net-tools', 'rsync', 'curl' ]
    state: latest
    update_cache: yes

- name: Enable syntax highlighting in vim
  lineinfile:
    dest: /etc/vim/vimrc
    regexp: '^syn'
    line: 'syntax on'
    create: true

- name: Enable line endings in vim
  lineinfile:
    dest: /etc/vim/vimrc
    regexp: '^set nu'
    line: 'set nu'
    create: true

- name: Disable password authentication for ssh
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp='PasswordAuthentication (yes|no)'
    line='PasswordAuthentication no'
  notify: restart ssh

- name: Restrict ssh for root to keys only
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp=^PermitRootLogin
    line='PermitRootLogin without-password'
  notify: restart ssh

- name: Change root password
  user:
    name: root
    password: "{{ lookup('template', 'standard_pw_gen.jinja2', template_vars=dict(name='root')) | password_hash('sha512') }}"
    update_password: always
  tags: pw

- name: Set hostname
  hostname:
    name: "{{ host.name }}"

- name: Set hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ host.name }}"

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: latest

- name: Configure DHCP Client
  template:
    src: dhcpcd.conf
    dest: /etc/dhcpcd.conf
  notify: restart dhcpcd

- meta: flush_handlers

- name: Setup swap
  include: swap.yml

- name: Update and upgrade packages
  apt:
    upgrade: safe
    update_cache: yes
