- name: Disable password authentication for ssh
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp='PasswordAuthentication (yes|no)'
    line='PasswordAuthentication no'
  notify: restart ssh

- name: Restrict ssh for root to keys only
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp=^PermitRootLogin
    line='PermitRootLogin without-password'
  notify: restart ssh

- name: Change root password
  user:
    name: root
    password: "{{ lookup('template', 'standard_pw_gen.jinja2', template_vars=dict(name='root')) | password_hash('sha512') }}"
    update_password: on_create
  tags: pw

# ceph-ansible deploys chrony
# - block:
#     - name: Enable NTP
#       include_role:
#         name: stuvusit.systemd-timesyncd
#       vars:
#         timesync_timezone: "{{ timezone }}"
#         timesync_ntp_hosts: "{{ ntp_servers }}"
#   tags: ntp

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - python3
      - python3-dev
      - python3-pip
      - bash-completion
      - git
      - htop
      - lsb-release
      - ncdu
      - tree
      - vim
      - wget
      - aptitude
      - fail2ban
      - net-tools
      - rsync
      - curl
      - ntp
      - dnsutils
      - tcpdump
      - tmux
      - lvm2
      - smartmontools
      - jq
      - nload

- include_tasks: vim.yml
  tags: vim

- name: Set hostname
  hostname:
    name: "{{ host.name }}"

- name: Set hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ host.name }}"

- include_tasks: unattended_upgrades.yml
  tags: unattended_upgrades

- include: network.yml
  when: not is_dev
  tags: network

#- include: promiscuous_mode.yml
#  tags: network

- include: sysctl.yml

- meta: flush_handlers

- name: Set timezone
  timezone:
    name: Europe/Zurich

- include_tasks: swap.yml

- name: Disable autocomplete beep
  lineinfile:
    path: /etc/inputrc
    regexp: '^(# )?set bell-style none'
    line: "set bell-style none"
  tags: bell_beep

- include_tasks: tools.yml
  tags: tools

- name: Update and upgrade packages
  apt:
    upgrade: safe
    update_cache: yes

- name: Copy resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644

- name: Create global certs dir
  file:
    path: "{{ global_cert_dir }}"
    state: directory

- block:
    - name: Setup dev environment
      include_tasks: dev_environment.yml
  when: is_dev
  tags: setup_dev
