- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - python3
      - python3-dev
      - python3-pip
      - python-dev
      - bash-completion
      - git
      - htop
      - lsb-release
      - ncdu
      - tree
      - vim
      - wget
      - aptitude
      - fail2ban
      - net-tools
      - rsync
      - curl
      - ntp
      - dnsutils
      - tcpdump

- include: vim.yml
  tags: vim

- name: Disable password authentication for ssh
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp='PasswordAuthentication (yes|no)'
    line='PasswordAuthentication no'
  notify: restart ssh

- name: Restrict ssh for root to keys only
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp=^PermitRootLogin
    line='PermitRootLogin without-password'
  notify: restart ssh

- name: Change root password
  user:
    name: root
    password: "{{ lookup('template', 'standard_pw_gen.jinja2', template_vars=dict(name='root')) | password_hash('sha512') }}"
    update_password: on_create
  tags: pw

- name: Set hostname
  hostname:
    name: "{{ host.name }}"

- name: Set hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ host.name }}"

- include: unattended_upgrades.yml
  tags: unattended_upgrades

- include: network.yml
  when: "'development' not in group_names"
  tags: network

- meta: flush_handlers

- name: Set timezone
  timezone:
    name: Europe/Zurich

- include: swap.yml

- name: Disable autocomplete beep
  lineinfile:
    path: /etc/inputrc
    regexp: '^(# )?set bell-style none'
    line: "set bell-style none"
  tags: bell_beep

- name: Update and upgrade packages
  apt:
    upgrade: safe
    update_cache: yes

- name: Copy resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644
