- name: Stop dhcpcd client
  service:
    name: dhcpcd
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Remove DHCP client
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - dhcpcd5
      - isc-dhcp-client
      - isc-dhcp-common

- name: Configure static IPs
  template:
    src: interfaces
    dest: /etc/network/interfaces
  tags: net_conf
  notify: restart computer

- name: Copy sysctl config for static ipv6
  template:
    src: ipv6-sysctl.conf
    dest: /etc/sysctl.d/80-ipv6.conf
    mode: 0644
  when: host.supports_v6
  tags: net_conf
  notify: restart computer

- meta: flush_handlers
