netdata:
  name: netdata
  user: netdata

duplicati:
  user: "{{ user }}"
  volumes:
    config:
      name: duplicati_config
      local_folder: "{{ root_dirs.maintenance }}/duplicati_config"
      mount: /config
    backup_target:
      name: duplicati_backup_target
      local_folder: "/home/{{ user }}"
      mount: "/source"

portainer:
  user: "{{ user }}"
  volumes:
    data:
      name: portainer_data
      local_folder: "{{ root_dirs.maintenance }}/portainer_config"
      mount: /data

maintenance_folders_permissions:
  - folder: "{{ duplicati.volumes.config }}"
    user: "{{ duplicati.user }}"
  - folder: "{{ portainer.volumes.data }}"
    user: "{{ portainer.user }}"
