netdata:
  name: netdata
  user: netdata

duplicati:
  user: "{{ user }}"
  volumes:
    config:
      name: duplicati_config
      local_folder: "{{ root_dirs.maintenance }}/duplicati_config"
      mount: /config
    backup_target:
      name: duplicati_backup_target
      local_folder: "/home/{{ user }}"
      mount: "/source"

portainer:
  user: "{{ user }}"
  volumes:
    data:
      name: portainer_data
      local_folder: "{{ root_dirs.maintenance }}/portainer_config"
      mount: /data

updater:
  ignore:
    - "openvpn"
    - "syslog_interceptor"
    - "datastore_syslog_interceptor"
    - "discord_discord_music_bot_1"
    - "jupyter_jupyter_1"
    - "realmarnet_realmar.net_1"
    - "pihole_dhcphelper_1"
    - "jupyter_jupyter"
    - "realmarnet_realmar.net"
    - "pihole_dhcphelper"

backup_helper:
  exclude:
    - realmarnet
    - jupyter
    - freshrss
    - openvpn
    - dhcphelper
    - unbound
    - netdata
    - authelia
    - traefik
    - syslog_interceptor
    - discord
    - duplicati

maintenance_folders_permissions:
  - folder: "{{ duplicati.volumes.config }}"
    user: "{{ duplicati.user }}"
  - folder: "{{ portainer.volumes.data }}"
    user: "{{ portainer.user }}"
