datastore_networks:
  v4:
    subnet:     172.16.80.0/24
    netaddress: 172.16.80.0
    netmask:    255.255.255.0
    gateway:    172.16.80.1
  name: "{{ network_names_datastore }}"

telegraf_syslog_port: 6518

influxdb_volumes_data:
  name:         influxdb_data
  local_folder: "{{ root_dirs_datastore }}/influxdb-data"
  mount:        /var/lib/influxdb

chronograf_volumes_data:
  name:         chronograf_data
  local_folder: "{{ root_dirs_datastore }}/chronograf-data"
  mount:        /var/lib/chronograf

kapacitor_volumes_data:
  name:         kapacitor_data
  local_folder: "{{ root_dirs_datastore }}/kapacitor-data"
  mount:        /var/lib/kapacitor

grafana_volumes_data:
  name:         grafana_data
  local_folder: "{{ root_dirs_datastore }}/grafana-data"
  mount:        /var/lib/grafana

grafana_db_name: grafana
grafana_db_container_name: grafana_db

grafana_db_container_user: 999
grafana_db_container_group: 1000

grafana_db_volumes_data:
  name:         grafana_db_data
  local_folder: "{{ root_dirs_datastore }}/grafana-db-data"
  mount:        /var/lib/postgresql/data

syslog_interceptor_container_user: interceptor
syslog_interceptor_container_home: /home/interceptor
syslog_interceptor_container_app_dir: /home/interceptor/app

registry_user: 1000

registry_volumes_data:
  name:         registry_data
  local_folder: "{{ root_dirs_datastore }}/registry-data"
  mount:        /var/lib/registry

registry_volumes_certificates:
  name:         registry_certificates
  local_folder: "{{ root_dirs_datastore }}/registry-certificates"
  mount:        /certificates

registry_tls_key: "{{ registry_volumes_certificates.local_folder }}/registry.key"
registry_tls_crt: "{{ registry_volumes_certificates.local_folder }}/registry.crt"
registry_tls_csr: "{{ registry_volumes_certificates.local_folder }}/registry.csr"

redis_user: 999
redis_container_name: redis

redis_volumes_data:
  name:         redis_data
  local_folder: "{{ root_dirs_datastore }}/redis-data"
  mount:        /data

prometheus_user: nobody

prometheus_volumes_data:
  name:         prometheus_data
  local_folder: "{{ root_dirs_datastore }}/prometheus-data"
  mount:        /prometheus

prometheus_user_influxdb_name: prometheus

influxdb_dbs:
  - home_assistant
  - graphite
  - ouroboros
  - traefik
  - "{{ prometheus_user_influxdb_name }}"
  - "{{ vector_influxdb_database_name }}"

grafana_dbs_excludes_traefik: "(Query(`db=telegraf`) || Query(`db=graphite`) || Query(`db=ouroboros`) || Query(`db=traefik`) || Query(`db={{ prometheus_user_influxdb_name }}`) || PathPrefix(`/grafana/api/datasources/proxy/11/loki`))"

psu_stats_interval: 10

corsairmi_installation_path: /opt/corsairmi
corsairmi_binary: "{{ corsairmi_installation_path }}/corsairmi"

vector_api_port: 8686
vector_syslog_port: 6512
# vector_fluent_port: 24224

vector_volumes_data:
  name:         vector_data
  local_folder: "{{ root_dirs_datastore }}/vector-data"
  mount:        /var/lib/vector

vector_volumes_scripts:
  name:         vector_scripts
  local_folder: "{{ root_dirs_datastore }}/vector-scripts"
  mount:        /opt/vector/scripts

vector_scripts_dir: "{{ vector_volumes_scripts.mount  }}"

vector_log_path: /opt/var/log

vector_influxdb_database_name: vector

loki_host: loki
loki_port: 3100
loki_endpoint: http://{{ loki_host }}:{{ loki_port }}

loki_volumes_data:
  name:         loki_data
  local_folder: "{{ root_dirs_datastore }}/loki-data"
  mount:        /data/loki

loki_volumes_wal:
  name:         loki_wal
  local_folder: "{{ root_dirs_datastore }}/loki-wal"
  mount:        /data/wal

# filebeat_syslog_port: 6812

# elastic_config_dir: "{{ root_dirs_datastore }}/elastic-config"

# fluentd_port: 24224

fluent_bit_tcp_input_port: 5170

fluent_bit_volumes_data:
  name:         fluent_bit_data
  local_folder: "{{ root_dirs_datastore }}/fluent_bit-data"
  mount:        /var/log/flb-storage

# mongodb_user: 999

# mongodb_volumes_data:
#   name:         mongodb_data
#   local_folder: "{{ root_dirs_datastore }}/mongodb-data"
#   mount:        /data/db

maxmind_volumes_data:
  name:         maxmind_data
  local_folder: "{{ root_dirs_datastore }}/maxmind-data"
  mount:        /usr/share/GeoIP
