- hosts: development
  gather_facts: yes
  remote_user: root

  roles:
    - { role: base_system, tags: base }
    - { role: docker, tags: docker }
    - { role: pihole, tags: pihole }
    - { role: vpn, tags: pihole }
    - { role: netdata, tags: monitoring }

  tasks:
    - name: Start docker containers
      docker_compose:
        project_src: "{{ item }}"
      with_items:
        - "{{ root_dirs.pihole }}"
        - "{{ root_dirs.netdata }}"
      tags:
        - initialize

  handlers:
    - import_tasks: handlers/services.yml
