- hosts: development
  gather_facts: yes
  remote_user: root
  debugger: on_failed

  pre_tasks:
    - include: tasks/collect_system_data.yml
      tags: always

  roles:
    - { role: pihole, tags: pihole }
    - { role: maintenance, tags: maintenance }
    - { role: fileserver, tags: fileserver }
    - { role: rss, tags: rss }

  post_tasks:
    # big hackkus, permissions should be set on deploy
    - name: Fix permissions
      file:
        path: "{{ item.volume.local_folder }}"
        owner: "{{ item.container.user }}"
        group: "{{ user }}"
        recurse: yes
      with_items: "{{ flat_volumes) }}"
      when: item.container.user is defined
      tags: permissions

    # I really don't want to install docker-compose via pip just to make the
    # docker_container module work. This is because pip install docker-compose
    # needs to compile a ton of C code and massively slows down the deployment
    - name: Start docker containers
      shell: "docker-compose up -d"
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ root_dirs.pihole }}"
        - "{{ root_dirs.maintenance }}"
        - "{{ root_dirs.rss }}"
      register: cli_result
      changed_when:
        - '"up-to-date" not in cli_result.stderr'
      tags:
        - initialize

  handlers:
    - import_tasks: handlers/services.yml
    - import_tasks: handlers/docker.yml
