- hosts: development
  gather_facts: yes
  remote_user: root

  roles:
    - base_system
    - docker
    - pihole
    - vpn
    - netdata

  tasks:
    - name: Start docker containers
      docker_compose:
        project_src: "{{ item }}"
      with_items:
        - "{{ root_dirs.pihole }}"
        - "{{ root_dirs.netdata }}"

  handlers:
    - import_tasks: handlers/services.yml
