- hosts: production
  gather_facts: yes
  remote_user: root
  debugger: on_failed

  roles:
    - { role: base_system, tags: base }
    - { role: docker, tags: docker }
    - { role: pihole, tags: pihole }
    - { role: vpn, tags: [ 'pihole', 'vpn' ] }
    - { role: netdata, tags: monitoring }

  tasks:
    - name: Start docker containers
      docker_compose:
        project_src: "{{ item }}"
      with_items:
        - "{{ root_dirs.pihole }}"
        - "{{ root_dirs.netdata }}"
      tags:
        - initialize
    
    - name: Fix permissions
      file:
        path: "{{ item.path }}"
        owner: "{{ item.user }}"
        group: "{{ item.group }}"
        recurse: yes
      with_items:
        - { path: "{{ root_dirs.pihole }}", user: "{{ pihole.user }}", group: "{{ user }}" }
        - { path: "{{ root_dirs.netdata }}", user: "{{ netdata.user }}", group: "{{ user }}" }
      tags: permissions

  handlers:
    - import_tasks: handlers/services.yml
