- hosts: all
  gather_facts: yes
  remote_user: root

#
# Define following vars
#   - vpn_username
#

  pre_tasks:
    - include: tasks/collect_system_data.yml
      tags: always

  roles:
    - new_ovpn_user
