#
# IN
#     command: string
#
# Examples:
#
# --extra-vars command='"docker-compose up -d --remove-orphans"'
# --extra-vars command='"docker-compose stop && docker-compose rm -f"'
# --extra-vars command='"docker-compose stop && docker-compose rm -f && docker-compose up -d --remove-orphans"'
#

- hosts: all
  gather_facts: yes
  remote_user: root
  debugger: on_failed

  pre_tasks:
    - include: tasks/collect_system_data.yml
      tags: always

  tasks:
    - name: Running command
      shell: "{{ command }}"
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ root_dirs.datastore }}"
        - "{{ root_dirs.proxy }}"
        - "{{ root_dirs.maintenance }}"
        - "{{ root_dirs.pihole }}"
        - "{{ root_dirs.home_automation }}"
        - "{{ root_dirs.rss }}"
        - "{{ root_dirs.jupyter }}"
        - "{{ root_dirs.personal_website }}"

    - name: Running command
      shell: "{{ command }}"
      args:
        chdir: "{{ item }}"
      with_items:
        #- "{{ root_dirs.discord }}"
        - "{{ root_dirs.matrix_server }}"
      when: not is_dev
