- hosts: development
  gather_facts: yes
  remote_user: root
  debugger: on_failed

  vars:
    restart_command: "docker-compose stop && docker-compose rm -f && docker-compose up -d"

  pre_tasks:
    - include: tasks/collect_system_data.yml
      tags: always

  tasks:
    - name: Recreate containers
      shell: "{{ restart_command }}"
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ root_dirs.pihole }}"
        - "{{ root_dirs.maintenance }}"
        - "{{ root_dirs.rss }}"
        - "{{ root_dirs.jupyter }}"
        - "{{ root_dirs.proxy }}"

    - name: Recreate containers
      shell: "{{ restart_command }}"
      args:
        chdir: "{{ item }}"
      with_items:
        - "{{ root_dirs.discord }}"
      when: not is_dev
