- hosts: all
  gather_facts: yes
  remote_user: root
  debugger: on_failed

  vars:
    restart_command: "docker-compose stop && docker-compose rm -f && docker-compose up -d --remove-orphans"

  pre_tasks:
    - include: tasks/init.yml
      tags: always

  tasks:
    - name: Recreate containers
      shell: "{{ restart_command }}"
      args:
        chdir: "{{ root_dirs.datastore }}"
