- hosts: all
  gather_facts: yes
  tasks:
    - include: tasks/collect_system_data.yml
      tags: always

- hosts: docker-swarm-manager[0]
  debugger: on_failed
  tasks:
    - debug:
        msg:
          - "{{ ansible_host }}"
          - "{{ inventory_hostname }}"
          - "{{ group_names }}"

          - "{{ is_rpi }}"
          - "{{ arch_short }}"
          - "{{ is_ubuntu }}"
          - "{{ is_debian }}"
          - "{{ is_dev }}"

- hosts: docker-swarm-manager:!docker-swarm-manager[0]
  debugger: on_failed

  tasks:
    - debug:
        msg:
          - "{{ ansible_host }}"
          - "{{ inventory_hostname }}"
          - "{{ group_names }}"

          - "{{ is_rpi }}"
          - "{{ arch_short }}"
          - "{{ is_ubuntu }}"
          - "{{ is_debian }}"
          - "{{ is_dev }}"

- hosts: docker-swarm-workers
  debugger: on_failed

  tasks:
    - debug:
        msg:
          - "{{ ansible_host }}"
          - "{{ inventory_hostname }}"
          - "{{ group_names }}"

          - "{{ is_rpi }}"
          - "{{ arch_short }}"
          - "{{ is_ubuntu }}"
          - "{{ is_debian }}"
          - "{{ is_dev }}"
