tls:
  certificates:
    - certFile: {{ traefik.volumes.certificates.mount }}/{{ tls.self_signed.cert }}
      keyFile:  {{ traefik.volumes.certificates.mount }}/{{ tls.self_signed.private_key }}
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: {{ traefik.volumes.certificates.mount }}/{{ tls.self_signed.cert }}
        keyFile:  {{ traefik.volumes.certificates.mount }}/{{ tls.self_signed.private_key }}
