- name: Install dphys-swapfile
  apt:
    name: 'dphys-swapfile'
    state: latest

- name: Copy swap config
  template:
    src: dphys-swapfile
    dest: /etc/dphys-swapfile
  register: copy_swapfile

- name: Setup swap
  command: dphys-swapfile setup
  when: copy_swapfile.changed

- name: Activate swap
  command: dphys-swapfile swapon
  when: copy_swapfile.changed

- name: Copy swap sysctls
  template:
    src: swap_sysctls.conf
    dest: /etc/sysctl.d/swap_sysctls.conf
    mode: 0644
  tags: swap_sysctls
  notify: apply sysctls
