# - include_tasks: create_user.yml
#   vars:
#     item: { name: "{{ unbound.user }}", uid: 107, create_home: no, groups: "" }

- name: Create unbound dirs
  file:
    path: "{{ folder }}"
    state: directory
    owner: "{{ unbound.user }}"
    group: "{{ user }}"
  loop:
    - "{{ unbound.volumes.main.local_folder }}"
    - "{{ unbound.volumes.main.local_folder }}/var"
  loop_control:
    loop_var: folder

- name: Copy config files
  template:
    src: "unbound/{{ file }}"
    dest: "{{ unbound.volumes.main.local_folder }}/{{ file }}"
    owner: "{{ unbound.user }}"
    group: "{{ user }}"
  loop:
    - unbound.conf
    - a-records.conf
  loop_control:
    loop_var: file
  notify: restart unbound
  tags: unbound_conf

- name: Copy cron job
  template:
    src: unbound/download_unbound_root_hints
    dest: /etc/cron.d/download_unbound_root_hints
    mode: 0644

- name: Download root.hints
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: "{{ unbound.volumes.main.local_folder }}/var/root.hints"
    owner: "{{ unbound.user }}"
    group: "{{ user }}"

- name: Copy logrotate file
  template:
    src: unbound/unbound-logrotate
    dest: /etc/logrotate.d/unbound
    mode: 0644
  tags: logrotate
