tls:
  certificates:
    - certFile: {{ traefik_volumes_certificates.mount }}/{{ tls_self_signed_cert }}
      keyFile:  {{ traefik_volumes_certificates.mount }}/{{ tls_self_signed_private_key }}
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: {{ traefik_volumes_certificates.mount }}/{{ tls_self_signed_cert }}
        keyFile:  {{ traefik_volumes_certificates.mount }}/{{ tls_self_signed_private_key }}
