- include_tasks: create_user.yml
  vars:
    item: { name: "{{ netdata.user }}", uid: 201, create_home: no, groups: "" }

- name: Create project folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ netdata.user }}"
    group: "{{ user }}"
  with_items:
    - "{{ root_dirs.netdata }}"
    # - "{{ volumes.netdata.main.local_folder }}"

- name: Copy docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ root_dirs.netdata }}"
    owner: "{{ netdata.user }}"
    group: "{{ user }}"
    mode: 0644
  tags: compose_file