- name: Create discovery network
  include_tasks: network/add_docker_network.yml
  vars:
    network: "{{ traefik.networks }}"

- block:
  - include_tasks: standard_service.yml
    vars:
      usr: "{{ user }}"
      root_dir: "{{ root_dirs.proxy }}"
      dirs: []
  tags: compose_file

# - block:
#   - include_tasks: fix_permissions.yml
#     vars:
#       items: "{{ rss_folders_permissions }}"
#   tags: fix_permissions
