- block:
  - name: Create discovery network
    include_tasks: containers/network/add_network.yml
    vars:
      network: "{{ traefik_networks }}"
  tags: docker_network

- block:
  - include_tasks: standard_service.yml
    vars:
      root_dir:
        path: "{{ root_dirs_proxy }}"
        user: "{{ proxy_container_user }}"
      dirs:
        - path: "{{ traefik_volumes_dynamic_conf.local_folder }}"
          user: "{{ proxy_container_user }}"

        - path: "{{ traefik_volumes_certificates.local_folder }}"
          user: "{{ proxy_container_user }}"

        - path: "{{ authelia_volumes_config.local_folder }}"
          user: "{{ proxy_container_user }}"

        - path: "{{ authelia_volumes_data.local_folder }}"
          user: "{{ proxy_container_user }}"

        - path: "{{ static_data_volumes_data.local_folder }}"
          user: "{{ proxy_container_user }}"

        - path: "{{ proxy_db_volumes_data.local_folder }}"
          user: "{{ proxy_db_container_user }}"
          group: "{{ proxy_db_container_group }}"
  tags:
    - compose_file
    - proxy_compose_file

- name: Copy traefik dynamic config
  template:
    src: "traefik_dynamic_config/{{ item }}"
    dest: "{{ traefik_volumes_dynamic_conf.local_folder }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    - tls_conf.yml
    - backup.yml
  tags: treafik_config

- name: Copy authelia config
  template:
    src: "authelia/{{ item }}"
    dest: "{{ authelia_volumes_config.local_folder }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    - configuration.yml
    - users_database.yml
  tags: auth_config

- name: Copy nginx config
  template:
    src: nginx.conf
    dest: "{{ root_dirs_proxy }}/nginx.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: static_data_config

- block:
  - include_tasks: tls/self_signed.yml
  tags:
    - tls
    - ssl

- block:
  - include_tasks: tls/extract_certs.yml
  tags:
    - tls
    - ssl
  when: not is_dev
