- name: Create discovery network
  include_tasks: docker/network/add_docker_network.yml
  vars:
    network: "{{ traefik.networks }}"

- block:
  - include_tasks: standard_service.yml
    vars:
      usr: "1000"
      root_dir: "{{ root_dirs.proxy }}"
      dirs:
        - "{{ traefik.volumes.dynamic_conf.local_folder }}"
        - "{{ traefik.volumes.certificates.local_folder }}"
        - "{{ authelia.volumes.config.local_folder }}"
        - "{{ authelia.volumes.data.local_folder }}"
  tags:
    - compose_file
    - proxy_compose_file

- name: Copy traefik config
  template:
    src: tls_conf.yml
    dest: "{{ traefik.volumes.dynamic_conf.local_folder }}/tls_conf.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: treafik_config

- name: Copy authelia config
  template:
    src: "authelia/{{ item }}"
    dest: "{{ authelia.volumes.config.local_folder }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    - configuration.yml
    - users_database.yml
  tags: auth_config

- block:
  - include_tasks: tls/self_signed.yml
  tags:
    - tls
    - ssl

# - block:
#   - include_tasks: fix_permissions.yml
#     vars:
#       items: "{{ rss_folders_permissions }}"
#   tags: fix_permissions
