#
# IN
#     items: list[
#                    {
#                         folder: string
#                         user: string
#                         group: string
#                    }
#                ]
#

# big hackkus, permissions should be set on deploy
- name: Fix permissions
  file:
    path: "{{ item.folder }}"
    owner: "{{ item.user }}"
    group: "{{ item.group if item.group is defined else item.user }}"
    recurse: yes
  with_items: "{{ items }}"
