- name: Install haveged for more entropy (OpenVPN needs to generate certificates which is brutally slow on a RPI)
  apt:
    name: haveged
    state: latest

- name: Start and enable haveged service
  service:
    name: haveged
    state: started
    enabled: yes

#- include_tasks: build.openvpn.rpi.yml
#  when: is_rpi

- name: Create VPN config folder
  file:
    path: "{{ openvpn_volumes_config }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if OpenVPN config exists
  stat:
    path: "{{ openvpn_volumes_config.local_folder }}/openvpn.conf"
  register: ovpn_conf

- name: Generate OpenVPN config
  shell: "docker run -v {{ openvpn_volumes_config.local_folder }}:{{ openvpn_volumes_config.mount }} --rm kylemanna/openvpn ovpn_genconfig -n {{ host_ipv4 if pihole_use_host_net else pihole_ipv4 }} -u udp://{{ openvpn_conf_dns }} -T {{ openvpn_conf_tls_cipher }} -C '{{ openvpn_conf_cipher }}' -a '{{ openvpn_conf_auth }}'"
  when: ovpn_conf.stat.exists == false

- name: Copy OpenVPN server conf
  template:
    src: openvpn/openvpn.conf
    dest: "{{ openvpn_volumes_config.local_folder }}"
    owner: "{{ openvpn_user }}"
    group: "{{ user }}"
    mode: 0644
  notify:
    - restart openvpn
  tags:
    - vpn_conf

- include_tasks: deploy_ca_cert.yml

- include_tasks: route_lan.yml
  tags: vpn_route_lan
