- name: Install haveged for more entropy (OpenVPN needs to generate certificates which is brutally slow on a RPI)
  apt:
    name: haveged
    state: latest

- name: Start and enable haveged service
  service:
    name: haveged 
    state: started
    enabled: yes

- name: Check if is rasbian
  stat:
    path: /usr/bin/raspi-config
  register: raspi_config_check

- set_fact:
    is_rasbian: "{{ raspi_config_check.stat.exists }}"

- include_tasks: build.openvpn.rpi.yml
  when: is_rasbian

- name: Create VPN config folder
  file:
    path: "{{ volumes.vpn.config }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check if OpenVPN config exists
  stat:
    path: "{{ volumes.vpn.config.local_folder }}/openvpn.conf"
  register: ovpn_conf

- name: Generate OpenVPN config
  shell: "docker run -v {{ volumes.vpn.config.local_folder }}:{{ volumes.vpn.config.mount }} --rm kylemanna/openvpn ovpn_genconfig -n {{ host.ipv4 if pihole.use_host_net else pihole.ipv4 }} -u udp://{{ openvpn.conf.dns }} -T {{ openvpn.conf.tls_cipher }} -C '{{ openvpn.conf.cipher }}' -a '{{ openvpn.conf.auth }}'"
  when: ovpn_conf.stat.exists == false

- name: Copy OpenVPN server conf
  template:
    src: openvpn/openvpn.conf
    dest: "{{ volumes.vpn.config.local_folder }}"
    owner: "{{ openvpn.user }}"
    group: "{{ user }}"
    mode: 0644
  notify:
    - restart openvpn
  tags:
    - vpn_conf

- include_tasks: deploy_ca_cert.yml

- include_tasks: route_lan.yml
  when: openvpn.use_host_net
  tags: vpn_route_lan
