zigbee2mqtt:
  volumes:
    config:
      name: zigbee2mqtt-data
      local_folder: "{{ root_dirs.home_automation }}/zigbee2mqtt-data"
      mount: /app/data

mosquitto:
  ipv4: 172.16.22.28

  volumes:
    data:
      name: mosquitto-data
      local_folder: "{{ root_dirs.home_automation }}/mosquitto-data"
      mount: /mosquitto/data
    log:
      name: mosquitto-log
      local_folder: "{{ root_dirs.home_automation }}/mosquitto-log"
      mount: /mosquitto/log

home_assistant:
  volumes:
    config:
      name: home_assistant-config
      local_folder: "{{ root_dirs.home_automation }}/home_assistant-config"
      mount: /config
