- include_tasks: create_user.yml
  vars:
    item: { name: "{{ user }}", password: "{{ user_password }}", create_home: yes, groups: "docker" }

- name: Get UID of default user
  getent:
    database: passwd
    key: "{{ user }}"
  register: default_user_id
  tags: always

- set_fact:
    user_id: "{{ default_user_id['ansible_facts']['getent_passwd']['pi'][1] }}"
  tags: always
