- include_tasks: create_user.yml
  vars:
    item: { name: "{{ user }}", password: "{{ user_password }}", create_home: yes, groups: "docker" }

- name: Get UID of default user
  getent:
    database: passwd
    key: "{{ user }}"
  register: default_user_id_raw
  tags: always

- set_fact:
    default_user_id: "{{ default_user_id_raw['ansible_facts']['getent_passwd'][user][1] }}"
  tags: always

- name: Get UID of fileshare user
  getent:
    database: passwd
    key: "{{ fileserver_share_user }}"
  register: fileshare_user_id_raw
  tags: always

- set_fact:
    fileserver_user_id: "{{ fileshare_user_id_raw['ansible_facts']['getent_passwd'][fileserver_share_user][1] }}"
  tags: always
