users:
{% if is_dev %}
  # password: test
  testuser:
    displayname: 'Test User'
    password: '{CRYPT}$6$rounds=500000$Bui4ldW5hXOI9qwJ$IUHQPCusUKpTs/OrfE9UuGb1Giqaa5OZA.mqIpH.Hh8RGFsEBHViCwQDx6DfkGUiF60pqNubFBugfTvCJIDNw1'
    email: your@email.address
    groups:
      - admins
      - dev
{% endif %}

  realmar:
    displayname: 'Realmar'
    password: '{{ proxy_authelia_realmar_password }}'
    email: '{{ proxy_authelia_realmar_email }}'
    groups:
      - admins
      - dev
