{% import "docker_misc.jinja2" as dm with context -%}

version: "3"
services:
  discord_music_bot:
    build: .
    volumes:
      - "{{ root_dirs.discord }}/config/config.txt:{{ discord_music_bot.home }}/config.txt:ro"
      - "{{ root_dirs.discord }}/config/serversettings.json:{{ discord_music_bot.home }}/serversettings.json:rw"
    {{ dm.restart_policy() }}
