traefik:
  lets_encrypt:
    resolver_name: "{{ letsencrypt_resolver_name }}"
    email: anastassios.martakos@outlook.com

  volumes:
    dynamic_conf:
      name:         traefik_dynamic_conf
      local_folder: "{{ root_dirs.proxy }}/traefik-dynamic-conf-data"
      mount:        /etc/traefik/dynamic_conf
    certificates:
      name:         traefik_certificates
      local_folder: "{{ root_dirs.proxy }}/traefik-certificates"
      mount:        /etc/traefik/certs

  networks:
    v4:
      subnet:     172.16.20.0/24
      netaddress: 172.16.20.0
      netmask:    255.255.255.0
      gateway:    172.16.20.1
    name: "{{ network_names.discovery }}"

authelia:
  protected_domains:
    - "{{ dns.public.root }}"
    - "{{ dns.internal.root }}"
    - "*.{{ dns.public.root }}"
    - "*.{{ dns.internal.root }}"

  volumes:
    config:
      name:         authelia_config
      local_folder: "{{ root_dirs.proxy }}/authelia-config"
      mount:        /config
    data:
      name:         authelia_data
      local_folder: "{{ root_dirs.proxy }}/authelia-data"
      mount:        /app/data

static_data:
  volumes:
    data:
      name:         static_data
      local_folder: "{{ root_dirs.proxy }}/static-data"
      mount:        /usr/share/nginx/html

tls:
  self_signed:
    cert:         realmar.net.crt
    private_key:  realmar.net.pem
    cert_request: realmar.net.csr

    cert_dir:         "{{ traefik.volumes.certificates.local_folder }}/realmar.net.crt"
    private_key_dir:  "{{ traefik.volumes.certificates.local_folder }}/realmar.net.pem"
    cert_request_dir: "{{ traefik.volumes.certificates.local_folder }}/realmar.net.csr"
