- name: restart pihole
  include_tasks: restart_compose_container.yml
  vars:
    item:
      name: "{{ pihole_name }}"
      dir: "{{ root_dirs_pihole }}"
  ignore_errors: yes # yeet

- name: restart unbound
  include_tasks: restart_compose_container.yml
  vars:
    item:
      name: "{{ unbound_name }}"
      dir: "{{ root_dirs_pihole }}"
  ignore_errors: yes # yeet

- name: restart pihole project
  shell: "docker-compose restart"
  args:
    chdir: "{{ root_dirs_pihole }}"
  ignore_errors: yes # yeet
