#
# IN
#     item
#     {
#         name: string      - container name
#         dir: string       - docker compose project dir
#     }
#

#- shell: "docker container ls | grep {{ item.name }}"
#  register: exists
#  failed_when: false

- shell: "docker-compose restart {{ item.name }}"
  args:
    chdir: "{{ item.dir }}"
#  when: exists.rc == 0
  ignore_errors: yes # yeet
