- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart computer
  reboot:
    reboot_timeout: 3600

- name: restart dhcpcd
  service:
    name: dhcpcd
    state: restarted
  ignore_errors: yes

- name: restart networking
  service:
    name: networking
    state: restarted
  ignore_errors: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
