- block:
    - include_tasks: standard_service.yml
      vars:
        root_dir:
          path: "{{ root_dirs_matrix_server }}"
          user: "{{ matrix_server_user }}"
        dirs:
          - path: "{{ matrix_server_volumes_data.local_folder }}"
            user: "{{ matrix_server_user }}"

          - path: "{{ matrix_server_db_volumes_data.local_folder }}"
            user: "{{ matrix_server_user }}"

          - path: "{{ matrix_server_telegram_volumes_data.local_folder }}"
            user: "{{ matrix_server_telegram_user }}"

          - path: "{{ matrix_server_whatsapp_volumes_data.local_folder }}"
            user: "{{ matrix_server_whatsapp_user }}"

          - path: "{{ matrix_server_signal_volumes_data.local_folder }}"
            user: "{{ matrix_server_signal_user }}"

          - path: "{{ matrix_server_signald_volumes_data.local_folder }}"
            user: "{{ matrix_server_signal_user }}"

          - path: "{{ matrix_server_instagram_volumes_data.local_folder }}"
            user: "{{ matrix_server_instagram_user }}"

          - path: "{{ matrix_server_twitter_volumes_data.local_folder }}"
            user: "{{ matrix_server_twitter_user }}"
  tags:
    - compose_file
    - matrix_server_compose_file

- name: Copy configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_volumes_data.local_folder }}/{{ item }}"
    owner: "{{ matrix_server_user }}"
    group: "{{ matrix_server_user }}"
    mode: 0644
  with_items:
    - homeserver.yaml
    - realmar.net.log.config
    - realmar.net.signing.key
  tags:
    - matrix_server_config
    - matrix_server_config_homeserver

- name: Copy DB scripts and configs
  template:
    src: "{{ item }}"
    dest: "{{ root_dirs_matrix_server }}/{{ item }}"
    owner: "{{ matrix_server_user }}"
    group: "{{ matrix_server_user }}"
    mode: 0644
  with_items:
    - init_db.sql
    - turnserver.conf
    - element_web_config.json
    - well-known_server.json
    - well-known_client.json
  tags:
    - matrix_server_config

- name: Copy telegram bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_telegram_volumes_data.local_folder }}/{{ item | replace('telegram-', '') }}"
    owner: "{{ matrix_server_telegram_user }}"
    group: "{{ matrix_server_telegram_user }}"
    mode: 0644
  loop:
    - telegram-config.yaml
    - telegram-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_telegram

- name: Copy whatsapp bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_whatsapp_volumes_data.local_folder }}/{{ item | replace('whatsapp-', '') }}"
    owner: "{{ matrix_server_whatsapp_user }}"
    group: "{{ matrix_server_whatsapp_user }}"
    mode: 0644
  loop:
    - whatsapp-config.yaml
    - whatsapp-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_whatsapp

- name: Copy signal bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_signal_volumes_data.local_folder }}/{{ item | replace('signal-', '') }}"
    owner: "{{ matrix_server_signal_user }}"
    group: "{{ matrix_server_signal_user }}"
    mode: 0644
  loop:
    - signal-config.yaml
    - signal-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_signal

- name: Copy instagram bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_instagram_volumes_data.local_folder }}/{{ item | replace('instagram-', '') }}"
    owner: "{{ matrix_server_instagram_user }}"
    group: "{{ matrix_server_instagram_user }}"
    mode: 0644
  loop:
    - instagram-config.yaml
    - instagram-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_instagram

- name: Copy twitter bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_twitter_volumes_data.local_folder }}/{{ item | replace('twitter-', '') }}"
    owner: "{{ matrix_server_twitter_user }}"
    group: "{{ matrix_server_twitter_user }}"
    mode: 0644
  loop:
    - twitter-config.yaml
    - twitter-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_twitter

- block:
  - name: Create python plugin folder
    file:
      path: "{{ matrix_server_python_plugins_path }}"
      state: directory
      owner: "{{ matrix_server_user }}"
      group: "{{ matrix_server_user }}"

  - name: Copy python plugins
    copy:
      src: "{{ item }}"
      dest: "{{ matrix_server_python_plugins_path }}/{{ item }}"
      owner: "{{ matrix_server_twitter_user }}"
      group: "{{ matrix_server_twitter_user }}"
      mode: 0644
    with_items: "{{ matrix_server_python_plugins }}"
  tags: matrix_python_plugins
