- block:
    - name: Get UID of default user
      getent:
        database: passwd
        key: "{{ user }}"
      register: matrix_server_default_user

    - set_fact:
        default_user_id: "'{{ matrix_server_default_user['ansible_facts']['getent_passwd']['pi'][1] }}'"

    - include_tasks: standard_service.yml
      vars:
        usr: "{{ matrix_server_user }}"
        root_dir: "{{ root_dirs_matrix_server }}"
        dirs:
          - "{{ matrix_server_volumes_data.local_folder }}"
          - "{{ matrix_server_db_volumes_data.local_folder }}"
          - "{{ matrix_server_telegram_volumes_data.local_folder }}"
          - "{{ matrix_server_signal_volumes_data.local_folder }}"
          - "{{ matrix_server_signald_volumes_data.local_folder }}"
  tags:
    - compose_file
    - matrix_server_compose_file

- name: Copy configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_volumes_data.local_folder }}/{{ item }}"
    owner: "{{ matrix_server_user }}"
    group: "{{ matrix_server_user }}"
    mode: 0644
  with_items:
    - homeserver.yaml
    - realmar.net.log.config
    - realmar.net.signing.key
  tags: matrix_server_config

- name: Copy DB scripts and configs
  template:
    src: "{{ item }}"
    dest: "{{ root_dirs_matrix_server }}/{{ item }}"
    owner: "{{ matrix_server_user }}"
    group: "{{ matrix_server_user }}"
    mode: 0644
  with_items:
    - init_db.sql
    - turnserver.conf
    - element_web_config.json
    - well-known_server.json
    - well-known_client.json
  tags:
    - matrix_server_config

- name: Copy telegram bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_telegram_volumes_data.local_folder }}/{{ item | replace('telegram-', '') }}"
    owner: "{{ matrix_server_telegram_user }}"
    group: "{{ matrix_server_telegram_user }}"
    mode: 0644
  loop:
    - telegram-config.yaml
    - telegram-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_telegram

- name: Copy signal bridge configs
  template:
    src: "{{ item }}"
    dest: "{{ matrix_server_signal_volumes_data.local_folder }}/{{ item | replace('signal-', '') }}"
    owner: "{{ matrix_server_signal_user }}"
    group: "{{ matrix_server_signal_user }}"
    mode: 0644
  loop:
    - signal-config.yaml
    - signal-registration.yaml
  tags:
    - matrix_server_config
    - matrix_server_signal

- block:
  - include_tasks: fix_permissions.yml
    vars:
      items: "{{ [
        (matrix_server_telegram_volumes_data, matrix_server_telegram_user),
        (matrix_server_signal_volumes_data, matrix_server_signal_user),
        (matrix_server_signald_volumes_data, matrix_server_signal_user)
         ] | volumes_to_permissions }}"
  tags:
    - fix_permissions
    - compose_file
    - matrix_server_compose_file
