{% import "docker/misc.jinja2" as dm with context -%}
{% import "docker/network.jinja2" as dn with context -%}
{% import "docker/volumes.jinja2" as dv with context -%}

{% set zigbee2mqtt_vols = [ zigbee2mqtt.volumes.config ] %}
{% set mosquitto_vols = [ mosquitto.volumes.data, mosquitto.volumes.log ] %}
{% set home_assistant_vols = [ home_assistant.volumes.config ] %}

version: "3"
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      mqtt:
    {{ dv.volumes_section_complete(zigbee2mqtt_vols)|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}

  mosquitto:
    image: eclipse-mosquitto
    networks:
      mqtt:
      {{ network_names.datastore }}:
    {{ dn.map_ports([ (1883,) ])|indent(width = 4) }}
    {{ dv.volumes_section_complete(mosquitto_vols)|indent(width = 4) }}
      - "{{ root_dirs.home_automation }}/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    {{ dm.common()|indent(width = 4) }}

  home_assistant:
    image: homeassistant/home-assistant:stable
    {{ lookup('traefik', { 'domain': dns_sub_domains.smarthome, 'service_name': 'smarthome', 'port': 8123, 'use_dns_root': True })|indent(width = 4) }}
    networks:
      {{ network_names.discovery }}:
      {{ network_names.datastore }}:
      mqtt:
    {{ dn.map_ports([ (8123,) ])|indent(width = 4) }}
    {{ dv.volumes_section_complete(home_assistant_vols)|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}

{{ dn.networks_declaration([ discovery_network, datastore_network ]) }}
  mqtt:

{{ dv.volumes_declaration(zigbee2mqtt_vols + mosquitto_vols + home_assistant_vols) }}
