# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

  # Text to speech
  tts:
    - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

influxdb:
  host: influxdb
  port: 8086
  ssl: false
  database: home_assistant
  max_retries: 8
  default_measurement: state

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - {{ traefik_networks.v4.subnet }}

logger:
  default: info
