- name: Install haveged for more entropy (OpenVPN needs to generate certificates which is brutally slow on a RPI)
  apt:
    name: haveged
    state: latest

- name: Start and enable haveged service
  service:
    name: haveged 
    state: started
    enabled: yes

- name: Check if is rasbian
  stat:
    path: /usr/bin/raspi-config
  register: raspi_config_check

- set_fact:
    is_rasbian: "{{ raspi_config_check.stat.exists }}"

- include: build.openvpn.rpi.yml
  when: is_rasbian

- name: Generate OpenVPN config
  shell: "docker run -v {{ volumes.vpn.config.local_folder }}:{{ volumes.vpn.config.mount }} --rm kylemanna/openvpn ovpn_genconfig -n {{ pihole.ipv4 }} -u udp://{{ openvpn.dns }}"

- name: Copy OpenVPN server conf
  template:
    src: openvpn.conf
    dest: "{{ volumes.vpn.config.local_folder }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  notify:
    - restart openvpn
  tags: vpn_conf

- include: deploy_ca_cert.yml
