- block:
  - include_tasks: standard_service.yml
    vars:
      usr: "{{ fileserver_share_user }}"
      root_dir: "{{ root_dirs_drive }}"
      dirs: []
  tags:
    - compose_file
    - drive_compose_file

- name: Copy .filebrowser.json file
  template:
    src: .filebrowser.json
    dest: "{{ root_dirs_drive }}/.filebrowser.json"
    owner: "{{ fileserver_share_user }}"
    group: "{{ fileserver_share_user }}"
    mode: 0644
  tags: drive_config

- name: Create empty database file
  file:
    path: "{{ root_dirs_drive }}/filebrowser.db"
    owner: "{{ fileserver_share_user }}"
    group: "{{ fileserver_share_user }}"
    mode: 0644
    state: touch
  tags: drive_config
