- block:
  - include_tasks: standard_service.yml
    vars:
      usr: "{{ user }}"
      root_dir: "{{ root_dirs.home_automation }}"
      dirs:
        - "{{ zigbee2mqtt.volumes.config.local_folder }}"
        - "{{ mosquitto.volumes.data.local_folder }}"
        - "{{ mosquitto.volumes.log.local_folder }}"
        - "{{ home_assistant.volumes.config.local_folder }}"
  tags: compose_file

- name: Copy zigbee2mqtt configuration
  template:
    src: "zigbee2mqtt_configuration.yaml"
    dest: "{{ zigbee2mqtt.volumes.config.local_folder }}/configuration.yaml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: ha_config

- name: Copy eclipse-mosquitto configuration
  template:
    src: "mosquitto.conf"
    dest: "{{ root_dirs.home_automation }}/mosquitto.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: ha_config


- name: Create default configuration
  block:
  - include_tasks: docker/start_stack.yml
    vars:
      dir: "{{ root_dirs.home_automation }}"

  - name: Wait until Home Assistant has finished initializing
    wait_for:
      port: 8123
      state: present
      delay: 8

  - include_tasks: docker/stop_stack.yml
    vars:
      dir: "{{ root_dirs.home_automation }}"
  tags: ha_config

- name: Copy home assistant configuration
  template:
    src: "home_assistant_configuration.yaml"
    dest: "{{ home_assistant.volumes.config.local_folder }}/configuration.yaml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: ha_config
