filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: syslog
    format: rfc5424
    protocol.tcp:
      host: "localhost:{{ filebeat_syslog_port }}"

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts:
    - "logstash:5044"

output.elasticsearch.enabled: false
