---
network:
  version: 2
  renderer: networkd
  ethernets:
    {{ host_public_interface }}:
      dhcp4: false
{% if host_supports_v6 %}
      dhcp6: false
{% endif %}
      addresses:
        - {{ host_ipv4 }}/{{ host_networks.v4.netmask_short }}
{% if host_supports_v6 %}
        - "{{ host_ipv6 }}/{{ host_networks.v6.netmask }}"
      gateway6: "{{ host_networks.v6.gateway }}"
      # routes:
      #   - to: "::/0"
      #     via: "{{ host_networks.v6.gateway }}"
      #     on-link: true
      #     metric: 1024
{% endif %}
      gateway4: {{ host_networks.v4.gateway }}
      nameservers:
        addresses:
          - 127.0.0.1
          - 1.1.1.1
          - 1.0.0.1
{% if host_supports_v6 %}
          - "::1"
          - "2606:4700:4700::1111"
          - "2606:4700:4700::1001"
{% endif %}
