- block:
    - include_tasks: standard_service.yml
      vars:
        root_dir:
          path: "{{ root_dirs_rss }}"
          user: "{{ user }}"
        dirs:
          - path: "{{ freshrss_volumes_data.local_folder }}"
            user: "{{ freshrss_user }}"

          - path: "{{ freshrss_volumes_extensions.local_folder }}"
            user: "{{ freshrss_user }}"

          - path: "{{ rss_db_volumes_data.local_folder }}"
            user: "{{ rss_db_user }}"
  tags:
    - compose_file
    - rss_compose_file
