- name: Create project folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ root_dirs.autoupdate }}"

- name: Copy docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ root_dirs.autoupdate }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: compose_file
