netdata_name: netdata
netdata_user: netdata

duplicati_user: "{{ user }}"

duplicati_volumes_config:
  name: duplicati_config
  local_folder: "{{ root_dirs_maintenance }}/duplicati_config"
  mount: /config

duplicati_volumes_backup_target:
  name: duplicati_backup_target
  local_folder: "/home/{{ user }}"
  mount: "/source"

portainer_user: "{{ user }}"

portainer_volumes_data:
  name: portainer_data
  local_folder: "{{ root_dirs_maintenance }}/portainer_config"
  mount: /data

updater_ignore:
  - "syslog_interceptor"
  - "datastore_syslog_interceptor"
  - "discord_music_bot_1"
  - "discord_among_us_server_1"
  - "jupyter_jupyter_1"
  - "realmarnet_realmar.net_1"
  - "pihole_dhcphelper_1"
  - "jupyter_jupyter"
  - "realmarnet_realmar.net"
  - "pihole_dhcphelper"
  - "zhawiot1_home_controller_1"

backup_helper_exclude:
  - realmarnet
  - jupyter
  - freshrss
  - dhcphelper
  - unbound
  - netdata
  - authelia
  - traefik
  - syslog_interceptor
  - discord
  - duplicati
  - among_us
  - redis
  - zhaw

maintenance_folders_permissions:
  - folder: "{{ duplicati_volumes_config }}"
    user: "{{ duplicati_user }}"
  - folder: "{{ portainer_volumes_data }}"
    user: "{{ portainer_user }}"
