- block:
    - include_tasks: standard_service.yml
      vars:
        root_dir:
          path: "{{ root_dirs_discord }}"
          user: "{{ music_bot_user }}"
        dirs:
          - path: "{{ anastassios_updater_volumes_data.local_folder }}"
            user: "{{ music_bot_uid }}"

          - path: "{{ root_dirs_discord }}/config"
            user: "{{ music_bot_uid }}"
  tags:
    - compose_file
    - discord_compose_file

- include_tasks: music_bot.yml
- include_tasks: among_us_server.yml
