# - name: Uninstall conflicting dependencies
#   apt:
#     name: [ 'dnsmasq-base', 'dnsmasq', 'apache2' ]
#     state: absent

- include_tasks: create.pihole.user.yml
  tags: pihole_users

- name: Create pihole config folders
  file:
    state: directory
    path: "{{ folder.local_folder }}"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_user }}"
  loop:
    - "{{ pihole_volumes_main }}"
    - "{{ pihole_volumes_dnsmasq }}"
    - local_folder: "{{ root_dirs_pihole }}/dhcp-helper"
  loop_control:
    loop_var: folder
  tags: pihole_conf

- name: Copy dhcp-helper files
  template:
    src: "pihole/dhcp-helper/Dockerfile"
    dest: "{{ root_dirs_pihole }}/dhcp-helper/Dockerfile"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_user }}"
    mode: 0644
  tags:
    - pihole_conf
    - compose_file

- name: Copy dnsmaq config extension
  template:
    src: "pihole/{{ item }}"
    dest: "{{ pihole_volumes_dnsmasq.local_folder }}/{{ item }}"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_user }}"
    mode: 0644
  with_items:
    - 10-custom-dns.conf
    - 07-dhcp-options
  tags: pihole_conf

- name: Copy pihole-FTL.conf file
  template:
    src: pihole/pihole-FTL.conf
    dest: "{{ pihole_volumes_main.local_folder }}/pihole-FTL.conf"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_user }}"
    mode: 0644
  tags: pihole_conf

- name: Copy startup.sh file
  template:
    src: pihole/startup.sh
    dest: "{{ pihole_volumes_main.local_folder }}/startup.sh"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_user }}"
    mode: 0755
  tags:
    - pihole_conf
    - pihole_startup

- name: Install update gravity cronjob
  template:
    src: pihole/pihole_update_gravitas
    dest: /etc/cron.d/pihole_update_gravitas
    mode: 0644
  tags: cronjobs

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml
    dest: "{{ root_dirs_pihole }}/docker-compose.yml"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_user }}"
    mode: 0644
  # notify: restart pihole project
  tags:
    - compose_file
    - pihole_compose_file
