- block:
    - include_tasks: standard_service.yml
      vars:
        usr: "{{ user }}"
        root_dir: "{{ root_dirs.jupyter }}"
        dirs:
          - "{{ jupyter.volumes.data.local_folder }}"
  tags:
    - compose_file
    - jupyter_compose_file

- name: Copy docker files
  template:
    src: "{{ item }}"
    dest: "{{ root_dirs.jupyter }}/{{ item }}"
    owner: "{{ jupyter.user }}"
    group: "{{ jupyter.user }}"
    mode: 0644
  with_items:
    - Dockerfile
  tags:
    - compose_file
    - docker_file

- block:
    - include_tasks: fix_permissions.yml
      vars:
        items: "{{ jupyter_folders_permissions }}"
  tags:
    - fix_permissions
    - jupyter_compose_file
