- block:
    - include_tasks: standard_service.yml
      vars:
        root_dir:
          path: "{{ root_dirs_jupyter }}"
          user: "{{ user }}"
        dirs:
          - path: "{{ jupyter_volumes_data.local_folder }}"
            user: "{{ jupyter_uid }}"
  tags: compose_file

- name: Copy docker files
  template:
    src: "{{ item }}"
    dest: "{{ root_dirs_jupyter }}/{{ item }}"
    owner: "{{ jupyter_user }}"
    group: "{{ jupyter_user }}"
    mode: 0644
  with_items:
    - Dockerfile
  tags:
    - compose_file
    - docker_file
