- name: Install Docker dependencies
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common', 'python-docker', 'python-pexpect', 'python-pip', 'libffi-dev' ]
    state: latest
    update_cache: yes

- name: Check if is rasbian
  stat:
    path: /usr/bin/raspi-config
  register: raspi_config_check

- set_fact:
    is_rasbian: "{{ raspi_config_check.stat.exists }}"

- include_tasks: rasbian_stretch.yml
  when: is_rasbian and ansible_distribution_major_version|int == 9

- include_tasks: debian_platforms.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int > 9 or ansible_distribution == 'Ubuntu'

- meta: flush_handlers
