- name: Install Docker dependencies
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common', 'python-docker', 'python-pexpect' ]
    state: latest
    update_cache: yes

- include: rasbian.yml
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest
    executable: pip3

- meta: flush_handlers
