- name: Install Docker dependencies
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common', 'python-docker', 'python-pexpect', 'python-pip', 'libffi-dev' ]
    state: latest
    update_cache: yes

- include_tasks: rasbian_stretch.yml
  when: is_rpi and ansible_distribution_major_version|int == 9

- include_tasks: debian_platforms.yml
  when: is_debian and ansible_distribution_major_version|int > 9 or is_ubuntu

- meta: flush_handlers
