- name: Remove obsolete docker packages
  apt:
    name: [ 'docker', 'docker-engine', 'docker.io', 'containerd', 'runc' ]
    state: absent

- name: Get LSB release
  shell: lsb_release -cs
  register: lsb_release
  changed_when: False

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
    filename: docker

- name: Install Docker
  apt:
    name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
    state: latest
    update_cache: yes
  notify: restart computer
