# docker run -it --rm  -v /home/pi/bkp:/data -v /home/pi:/home/pi -p 8200:8200 duplicati/duplicati

{% import 'docker_volumes.jinja2' as dv with context -%}
{% import 'docker_network.jinja2' as dn with context -%}
{% import "docker_misc.jinja2" as dm with context -%}

{%- set vols = [
  duplicati.volumes.config,
  duplicati.volumes.backup_target
] -%}

duplicati:
  container_name: duplicati
  hostname: duplicati
  image: linuxserver/duplicati:latest
  environment:
    PUID: 0 # ding dong root bad
    PGID: 0 # ding dong root bad
    TZ: {{ timezone }}
    CLI_ARGS: --restore-permissions=true
  {{ dn.map_ports([ (8200, 8200) ])|indent(width = 2) }}
  {{ dv.volumes_section_complete(vols)|indent(width = 2) }}
  {{ dm.restart_policy() }}
