{%- import 'docker_volumes.jinja2' as dv with context -%}

portainer:
  container_name: portainer
  hostname: portainer
  image: portainer/portainer:latest
  ports:
    - 9000:9000
  {{ dv.volumes_section_complete([ volumes.portainer.data ])|indent(width = 2) }}
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
