{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/swarm.jinja2' as ds with context -%}
{% import 'traefik/http.jinja2' as traefik with context -%}

portainer:
  hostname: portainer
  image: portainer/portainer:latest
  command:
    - "--no-auth"
  {{ dv.volumes_section_complete([ portainer.volumes.data ])|indent(width = 2) }}
    - /var/run/docker.sock:/var/run/docker.sock
  {{ dn.discovery_network_section()|indent(width = 2) }}
  {{ ds.deploy_section()|indent(width = 2) }}
    {{ traefik.declare_labels_mount_path_internal("portainer", "/portainer", 9000)|indent(width = 4) }}
    {{ ds.placement_run_manager_section()|indent(width = 4) }}
