{%- import 'docker_volumes.jinja2' as dv with context -%}

ouroboros:
  container_name: ouroboros
  hostname: ouroboros
  image: pyouroboros/ouroboros:latest
  environment:
    - CLEANUP=true
    - INTERVAL=3600
    - LOG_LEVEL=info
    - SELF_UPDATE=true
    - IGNORE={% for c in containers_autoupdate_disabled %}{{ c.name }}{% endfor %}

  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    {{ dv.datetime_mapping()|indent(width = 4) }}
