{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/swarm.jinja2' as ds with context -%}

updater:
  image: mazzolino/shepherd:latest
  environment:
    SLEEP_TIME: "60m"
    WITH_INSECURE_REGISTRY: "true"
  {{ dv.volumes_section_complete()|indent(width = 2) }}
    {{ dv.mount_docker_socket() }}
  {{ ds.deploy_section()|indent(width = 2) }}
    {{ ds.placement_run_manager_section()|indent(width = 4) }}
