{% import 'utils.jinja2' as utils with context -%}
{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}

{# Unfortunately, the resource cost vs benefit is not justified for these #}
{# 'netdata.yml', #}
{# 'container_management.yml' #}
{% set services = [
  'docker_update.yml',
] %}

version: '3'
services:
{% for service in services %}
  {{ utils.include(service)|indent(width = 2) }}
{% endfor %}

{{ dn.networks_declaration([ discovery_network, datastore_network ]) }}

{#
{% set vols = [
  portainer_volumes_data
] %}
{{ dv.volumes_declaration(vols) }}
#}
