{%- import 'docker_volumes.jinja2' as dv with context -%}
{% import "docker_misc.jinja2" as dm with context -%}

ouroboros:
  container_name: ouroboros
  hostname: ouroboros
  image: pyouroboros/ouroboros:latest
  environment:
    - CLEANUP=true
    - INTERVAL=3600
    - LOG_LEVEL=info
    - SELF_UPDATE=true
    - IGNORE=openvpn
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    {{ dv.datetime_mapping()|indent(width = 4) }}
  {{ dm.restart_policy() }}
