{% import 'utils.jinja2' as utils with context -%}
{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}

{% set services = [
  'docker_update.yml',
  'netdata.yml',
  'container_management.yml',
  'mikrotik_exporter.yml'
] %}

version: '3'
services:
{% for service in services %}
  {{ utils.include(service)|indent(width = 2) }}
{% endfor %}

{{ dn.networks_declaration([ discovery_network, datastore_network ]) }}

{% set vols = [
  portainer_volumes_data
] %}
{{ dv.volumes_declaration(vols) }}
