{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/swarm.jinja2' as ds with context -%}
{% import 'traefik/http.jinja2' as traefik with context -%}

netdata:
  image: netdata/netdata:latest
  cap_add:
    - SYS_PTRACE
  security_opt:
    - apparmor:unconfined
  volumes:
    - {{ root_dirs.maintenance }}/netdata.conf:/etc/netdata/netdata.conf:ro
    - /etc/passwd:/host/etc/passwd:ro
    - /etc/group:/host/etc/group:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    {{ dv.datetime_mapping()|indent(width = 4) }}
  {{ dn.map_ports([ (19999,) ])|indent(width = 2) }}
  {{ dn.discovery_network_section()|indent(width = 2) }}
    {{ network_names.datastore }}:
  deploy:
    mode: global
    {{ ds.common()|indent(width = 4) }}
{# data collection is local to a single machine, it does not make sense to put them all behind a load balancer #}
{#  {{ traefik.declare_labels_mount_path_internal("netdata", "/netdata", 19999)|indent(width = 4) }} #}
