{%- import 'docker_volumes.jinja2' as dv with context -%}

netdata:
  container_name: {{ netdata.name }}
  image: netdata/netdata:latest
  hostname: pihole.home
  ports:
    - 19999:19999
  cap_add:
    - SYS_PTRACE
  security_opt:
    - apparmor:unconfined
  volumes:
    - /etc/passwd:/host/etc/passwd:ro
    - /etc/group:/host/etc/group:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    {{ dv.datetime_mapping()|indent(width = 4) }}
  restart: always
