{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/misc.jinja2' as dm with context -%}

netdata:
  container_name: {{ netdata_name }}
  image: netdata/netdata:latest
  hostname: pihole.home
  cap_add:
    - SYS_PTRACE
  security_opt:
    - apparmor:unconfined
  volumes:
    - {{ root_dirs_maintenance }}/netdata.conf:/etc/netdata/netdata.conf:ro
    - /etc/passwd:/host/etc/passwd:ro
    - /etc/group:/host/etc/group:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    {{ dv.datetime_mapping()|indent(width = 4) }}
  {{ lookup('traefik', { 'service_name': 'netdata', 'use_internal': True, 'port': 19999 })|indent(width = 2) }}
  {{ dn.discovery_network_section()|indent(width = 2) }}
    {{ network_names_datastore }}:
  {{ dm.common()|indent(width = 2) }}
