{% import 'docker/volumes.jinja2' as dv with context -%}
{% import 'docker/network.jinja2' as dn with context -%}
{% import 'docker/misc.jinja2' as dm with context -%}

{% set wireguard_vols = [ wireguard_volumes_config ] %}

version: "3"
services:
  {{ dm.service(
    'wireguard',
    'ghcr.io/linuxserver/wireguard:' + dm.autoarch('amd64-latest', 'arm64v8-latest'))|indent(width = 2) }}
    container_name: wireguard
    privileged: True
    {{ lookup('traefik', { 'service_name': 'wireguard', 'protocol': 'udp', 'port': 51820, 'entrypoints': [ 'wireguard_udp' ] })|indent(width = 4) }}
    {{ dv.volumes_section_complete(wireguard_vols)|indent(width = 4) }}
      - /lib/modules:/lib/modules
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dm.journald_logging()|indent(width = 4) }}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: {{ user_id }}
      PGID: {{ user_id }}
      TZ: {{ timezone }}
      SERVERURL: {{ dns_public_root }}
      SERVERPORT: 51820
      PEERS: phone,laptop
{#    PEERDNS: {{ host_ipv4 }} #}
      INTERNAL_SUBNET: 10.28.28.0
      ALLOWEDIPS: 0.0.0.0/0
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0

{{ dn.discovery_networks_declaration() }}

{{ dv.volumes_declaration(wireguard_vols) }}
