pihole_name: pihole

pihole_user: 999
pihole_group: 1000

pihole_dnsmasq_user: pihole

pihole_ipv4: 172.16.1.20
pihole_ipv6: 2a02:120b:2c06:57df::20

pihole_web_admin_port: 80

pihole_volumes_main:
  name: main_config
  local_folder: "{{ root_dirs_pihole }}/etc-pihole"
  mount: /etc/pihole/

pihole_volumes_dnsmasq:
  name: dnsmasq_config
  local_folder: "{{ root_dirs_pihole }}/etc-dnsmasq.d"
  mount: /etc/dnsmasq.d/

pihole_networks:
  v4:
    subnet: 172.16.1.0/24
    netaddress: 172.16.1.0
    netmask: 255.255.255.0
    gateway: 172.16.1.1
  v6:
    enable: "{{ host_supports_v6 }}"
    subnet: 2a02:120b:2c06:57df::/64
    netmask: 64
    gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
  name: pihole_net

unbound_name: unbound
unbound_user: "{{ user }}"
unbound_group: "{{ user }}"

unbound_ipv4: 172.16.3.20
unbound_port: 25353

unbound_volumes_main:
  name: unbound_config
  local_folder: "{{ root_dirs_pihole }}/etc-unbound"
  mount: /opt/unbound/etc/unbound

unbound_networks:
  v4:
    subnet: 172.16.3.0/24
    netaddress: 172.16.3.0
    netmask: 255.255.255.0
    gateway: 172.16.3.1
  name: unbound_net

pihole_prometheus_exporter_container_name: pihole_prometheus_exporter
pihole_prometheus_exporter_port: 9617
