pihole_name: pihole

pihole_user: 999
pihole_group: 1000

pihole_dnsmasq_user: pihole

pihole_ipv4: 172.16.1.20
pihole_ipv6: 2a02:120b:2c06:57df::20
pihole_use_host_net: no

pihole_discovery_ipv4: 172.16.20.20
pihole_web_bind_address: 172.16.20.20
pihole_web_admin_port: 80

pihole_volumes_main:
  name: main_config
  local_folder: "{{ root_dirs_pihole }}/etc-pihole"
  mount: /etc/pihole/

pihole_volumes_dnsmasq:
  name: dnsmasq_config
  local_folder: "{{ root_dirs_pihole }}/etc-dnsmasq.d"
  mount: /etc/dnsmasq.d/

pihole_networks:
  v4:
    subnet: 172.16.1.0/24
    netaddress: 172.16.1.0
    netmask: 255.255.255.0
    gateway: 172.16.1.1
  v6:
    enable: "{{ host_supports_v6 }}"
    subnet: 2a02:120b:2c06:57df::/64
    netmask: 64
    gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
  name: pihole_net

unbound_name: unbound
unbound_user: "{{ user }}"
unbound_group: "{{ user }}"

unbound_ipv4: 172.16.3.20
unbound_port: 25353
unbound_use_host_net: no

unbound_volumes_main:
  name: unbound_config
  local_folder: "{{ root_dirs_pihole }}/etc-unbound"
  mount: /opt/unbound/etc/unbound

unbound_networks:
  v4:
    subnet: 172.16.3.0/24
    netaddress: 172.16.3.0
    netmask: 255.255.255.0
    gateway: 172.16.3.1
  name: unbound_net

openvpn_name: openvpn
openvpn_user: "{{ user }}"
openvpn_group: "{{ user }}"
openvpn_ipv4: 172.16.2.20
openvpn_ipv6: 2a02:120b:2c06:57de::20
openvpn_pihole_ipv4: 172.16.1.80
openvpn_use_host_net: no
openvpn_autoupdate: no
openvpn_tun_device_name: tun0

openvpn_conf_dns: vpn.realmar.net
openvpn_conf_ca_cert_bits: 4096
openvpn_conf_tls_cipher: TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384
openvpn_conf_cipher: AES-256-GCM
openvpn_conf_auth: SHA512

openvpn_conf_server_v4:
  subnet: 192.168.255.0/24
  netaddress: 192.168.255.0
  netmask: 255.255.255.0

openvpn_conf_server_v6:
  netaddress: "2a02:120b:2c06:57dc::"
  netmask: 64

openvpn_conf_client_only_dns_over_vpn: yes

openvpn_volumes_config:
  name: ovpn_config
  local_folder: "{{ root_dirs_pihole }}/etc-openvpn"
  mount: /etc/openvpn

openvpn_networks:
  v4:
    subnet: 172.16.2.0/24
    netaddress: 172.16.2.0
    netmask: 255.255.255.0
    gateway: 172.16.2.1
  v6:
    enable: "{{ host_supports_v6 }}"
    subnet: 2a02:120b:2c06:57de::/64
    netmask: 64
    gateway: 2a02:120b:2c06:57d0:7eb7:33ff:fed0:41a6
  name: vpn_net
