{% import "docker/network.jinja2" as dn with context -%}
{% import "docker/misc.jinja2" as dm with context -%}
{% import "docker/swarm.jinja2" as ds with context -%}
{% import "traefik/http.jinja2" as tf with context -%}

{% set service_name = "realmar_net" %}
version: "3"
services:
  realmar_net:
    image: {{ dm.private_image('realmar_net') }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ ds.deploy_section()|indent(width = 4) }}
      {{ tf.declare_labels_mount_path_public(service_name, "/", 80, tf.minimal_middlewares_no_auth)|indent(width = 6) }}

{{ dn.discovery_networks_declaration() }}
