{% import "docker/network.jinja2" as dn with context -%}
{% import "docker/misc.jinja2" as dm with context -%}

version: "3"
services:
  realmar.net:
    image: {{ dm.private_image('realmar_net') }}
    {{ lookup('traefik', { 'service_name': 'realmar_net', 'use_dns_root': True })|indent(width = 4) }}
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dm.common()|indent(width = 4) }}

{{ dn.discovery_networks_declaration() }}
