{% import "docker/network.jinja2" as dn with context -%}
{% import "docker/misc.jinja2" as dm with context -%}
{% import "traefik/http.jinja2" as tf with context -%}

{% set service_name = "realmar_net" %}
version: "3"
services:
  realmar.net:
    build: .
    labels:
      {{ tf.enable(service_name)|indent(width = 6) }}
      {{ tf.use_letsencrypt(service_name) }}
      - "traefik.http.routers.{{ service_name }}.rule=Host(`{{ dns.public.root }}`)"
    {{ dn.discovery_network_section()|indent(width = 4) }}
    {{ dm.restart_policy() }}

{{ dn.discovery_networks_declaration() }}
