- block:
    - include_tasks: standard_service.yml
      vars:
        usr: "{{ user }}"
        root_dir: "{{ root_dirs_wireguard }}"
        dirs:
          - "{{ wireguard_volumes_config.local_folder }}"
  tags:
    - compose_file
    - wireguard_compose_file
