- block:
    - include_tasks: standard_service.yml
      vars:
        usr: "{{ user }}"
        root_dir: "{{ root_dirs_wireguard }}"
        dirs:
          - "{{ wireguard_volumes_config.local_folder }}"
  tags:
    - compose_file
    - wireguard_compose_file

- name: Copy wireguard sysctls
  template:
    src: wireguard_sysctls.conf
    dest: /etc/sysctl.d/wireguard_sysctls.conf
    mode: 0644
  tags: wireguard_sysctls
  notify: apply sysctls

- meta: flush_handlers
