- block:
    - include_tasks: standard_service.yml
      vars:
        root_dir:
          path: "{{ root_dirs_wireguard }}"
          user: "{{ user }}"
        dirs:
          - path: "{{ wireguard_volumes_config.local_folder }}"
            user: "{{ user }}"
  tags:
    - compose_file
    - wireguard_compose_file

# - name: Copy wireguard sysctls
#   template:
#     src: wireguard_sysctls.conf
#     dest: /etc/sysctl.d/wireguard_sysctls.conf
#     mode: 0644
#   tags: wireguard_sysctls
#   notify: apply sysctls
#
# - meta: flush_handlers
