- name: Create pihole user
  user:
    name: "{{ user }}"
    state: present
    shell: /bin/bash
    groups: docker
    create_home: yes
    password: "{{ lookup('password', user + '_password.txt chars=ascii_letters,digits,hexdigits,punctuation length=40') | password_hash('sha512') }}"
    update_password: always
  tags: pw

- name: Create pihole directory
  file:
    path: "{{ root_dirs.pihole }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
