- include_tasks: create_user.yml
  vars:
    item: { name: "{{ pihole.user }}", uid: 999, create_home: no, groups: "{{ user }}" }

- name: Create pihole directory
  file:
    path: "{{ root_dirs.pihole }}"
    state: directory
    owner: "{{ pihole.user }}"
    group: "{{ user }}"
