- name: Create pihole user
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: docker
    create_home: yes
    state: present

- name: Create pihole directory
  file:
    path: "{{ root_dirs.pihole }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
