- include_tasks: "{{ item }}"
  with_items:
    - pihole/main.yml
    - openvpn/main.yml
    - unbound/main.yml
  tags:
    - compose_file
    - pihole_compose_file

- block:
    - include_tasks: fix_permissions.yml
      vars:
        items: "{{ [ (pihole_volumes_main,    pihole_user),
                     (pihole_volumes_dnsmasq, pihole_user),
                     (unbound_volumes_main,   unbound_user),
                     (openvpn_volumes_config, openvpn_user) ] | volumes_to_permissions }}"
  tags: fix_permissions
