# - name: Uninstall conflicting dependencies
#   apt:
#     name: [ 'dnsmasq-base', 'dnsmasq', 'apache2' ]
#     state: absent

- include: create.pihole.user.yml
  tags: pihole_users

- name: Create pihole config folders
  file:
    state: directory
    path: "{{ item.local_folder }}"
    owner: "{{ pihole.user }}"
    group: "{{ user }}"
  with_items:
    - "{{ volumes.pihole.main }}"
    - "{{ volumes.pihole.dnsmasq }}"
  tags: pihole_conf

- name: Copy dnsmaq config extension
  template:
    src: 10-custom-dns.conf
    dest: "{{ volumes.pihole.dnsmasq.local_folder }}/10-custom-dns.conf"
    owner: "{{ pihole.user }}"
    group: "{{ user }}"
    mode: 0644
  tags: pihole_conf

- name: Copy pihole-FTL.conf file
  template:
    src: pihole-FTL.conf
    dest: "{{ volumes.pihole.main.local_folder }}/pihole-FTL.conf"
    owner: "{{ pihole.user }}"
    group: "{{ user }}"
    mode: 0644
  tags: pihole_conf

- name: Install update gravity cronjob
  template:
    src: pihole_update_gravitas
    dest: /etc/cron.d/pihole_update_gravitas
    mode: 0644
  tags: cronjobs

- include: docker_network.yml
  tags: docker_net

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml
    dest: "{{ root_dirs.pihole }}/docker-compose.yml"
    owner: "{{ pihole.user }}"
    group: "{{ user }}"
    mode: 0644
  notify: restart pihole project
  tags: compose_file

- import_role:
    name: vpn
  tags:
    - pihole
    - vpn

- import_role:
    name: unbound
  tags:
    - pihole
    - unbound
