# - name: Uninstall conflicting dependencies
#   apt:
#     name: [ 'dnsmasq-base', 'dnsmasq', 'apache2' ]
#     state: absent

- include: create.pihole.user.yml

- name: Create docker networks
  docker_network:
    name: "{{ item.name }}"
    driver: bridge
    enable_ipv6: no
    ipam_config:
      - subnet: "{{ item.v4.subnet }}"
        gateway: "{{ item.v4.gateway }}"
  with_items:
    - "{{ network.pihole }}"
    - "{{ network.vpn }}"
  tags: docker_network
  when: "{{ network.enable_ipv6 is False }}"

- name: Create docker networks
  docker_network:
    name: "{{ item.name }}"
    driver: bridge
    enable_ipv6: yes
    ipam_config:
      - subnet: "{{ item.v4.subnet }}"
        gateway: "{{ item.v4.gateway }}"
      - subnet: "{{ item.v6.subnet }}"
        gateway: "{{ item.v6.gateway }}"
  with_items:
    - "{{ network.pihole }}"
    - "{{ network.vpn }}"
  tags: docker_network
  when: "{{ network.enable_ipv6 }}"

- name: Copy dnsmaq config extension
  template:
    src: 10-custom-dns.conf
    dest: "{{ docker_volume_root }}/{{ pihole.volumes.dnsmaq }}/_data/10-custom-dns.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml
    dest: "{{ root_dirs.pihole }}/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: compose_file
