# - name: Uninstall conflicting dependencies
#   apt:
#     name: [ 'dnsmasq-base', 'dnsmasq', 'apache2' ]
#     state: absent

- include: create.pihole.user.yml

- name: Create pihole folders
  file:
    state: directory
    path: "{{ item.local_folder }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ volumes.pihole.main }}"
    - "{{ volumes.pihole.dnsmasq }}"
    - "{{ volumes.vpn.config }}"

- name: Copy dnsmaq config extension
  template:
    src: 10-custom-dns.conf
    dest: "{{ volumes.pihole.dnsmasq.local_folder }}/10-custom-dns.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml
    dest: "{{ root_dirs.pihole }}/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags: compose_file

- name: Install update gravity cronjob
  template:
    src: pihole_update_gravitas
    dest: /etc/cron.d/pihole_update_gravitas
    mode: 0644
  tags: cronjobs
